### ISSUE TITLE
TCPServer Remote Code Features Left TODO

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extDB2#10]
Stuff left to add

Blacklisting IP's from clients that fail to login 3 times
Ability to restrict to only certain IP's to Login

**Comment by chris579** [comment]
What about adding a ssh tunnel? Is it possible?

**Comment by Torndeco** [comment]
SSH Tunnels are out of scope for extDB2
If anyone codes one especially using ASIO i be interested etc

Its just going to be a basic client blacklisting, mainly for people running extDB2 on a GSP Server.

-------------------

Personally the best method is still going to be ssh tunnel into your server + tunnel the tcp connection through it.

**Comment by Torndeco** [comment]
Anyway blacklisting IP's is done... will be in next version.
Atleast now its harder to bruteforce guess the password.

But it is still better to tunnel raw TCP through a SSH tunnel.
