### ISSUE TITLE
entry point scaleable_free missing

### ISSUE THREAD

**Issue by MarkusSR1984** [Torndeco/extDB2#100]
v65 Error Message on Mission Start: 
entry point scaleable_free missing

used: a3_perf_v1,52v4
malloc: from fred41

current tbbmalloc from extDB2 v65

I switched back to v64 now.

i try to reproduce at my testserver to give you detailed Infomation if this come from extdb2.dll or not

**Comment by MarkusSR1984** [comment]
HI,

i tryed out a few combinations
error happens in combination with fred´s malloc for arma3server

-> your malloc in arma3server root directory
-> freds malloc in dll directory

http://fs5.directupload.net/images/151021/8on4u34e.png

without freds malloc extB2 v65 works well
but freds malloc is the best :(

**Comment by MarkusSR1984** [comment]
Same with v66

**Comment by Torndeco** [comment]
extDB2 is not compatiable with Fred's Malloc  is outdated...
You need to rename his malloc etc
