### ISSUE TITLE
Is extDB2 thread safe?

### ISSUE THREAD

**Issue by dbenson24** [Torndeco/extDB2#101]
Looking at the example async.sqf file, I noticed that there is no logic for handling numerous SQF threads trying to make calls to the extension at the same time. Is it safe to have multiple threads calling the extension simultaneously do I need to code in some sort of lock that only lets one thread call the extension at a time.

Thanks

**Comment by Torndeco** [comment]
extDB2 is coded to handle been called by multiple process threads at once.
Arma engine is not able todo this....... 

Also Arma SQF is basically single threaded regardless of spawn calls etc.
Also callExtension in arma blocks the engine it waits until the extension is done.

**Comment by chris579** [comment]
It is thread safe. Looking at asyncCall.sqf you can see that is repeating the execution when the extension got locked from another script  thread (return value `"[3]"`).

**Comment by dbenson24** [comment]
Thank you very much for the quick response.
