### ISSUE TITLE
Small issue with 9:LOCK

### ISSUE THREAD

**Issue by killerty69** [Torndeco/extDB2#102]
This isn't a big deal but would still be useful to have extdb give out more information. When you call add_database twice on the same db it will obviously tell you that the database was already added; however, if you call 9:LOCK and then attempt to do it nothing is return just an empty string. 
http://prntscr.com/8wx7ba

**Comment by Torndeco** [comment]
Use 9:LOCK_STATUS
To check the lock status before you do setup
