### ISSUE TITLE
extDB2: extDB2: Incompatible Config Version

### ISSUE THREAD

**Issue by MattDogIRC** [Torndeco/extDB2#103]
this is for exile on windows pasting my file
thanks for help in advanced

[Main]
Version = 5
;Threads = 0  
; Default Value is the number of CPU Cores Detected (max value is 6, min value is 2)
Randomize Config File = false
;This is a legacy option to randomize config file for Arma2 Servers.

[RemoteAccess]
;; Remote TCP Access to extDB2
Enable = false
Port = 2300
MaxThreads = 4
MaxQueued = 4
IdleTime = 120
Username = uyT46f3oT5 changeme

[Steam]
;; This is for VAC Protocol for VAC Bans + Steam Friends.
;; https://steamcommunity.com/dev/apikey
API Key = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

[VAC]
;; This feature requires Steam + Rcon to be enabled.
;; Also this feature is called via SQF Code atm, i.e it doesn't auto detect players joining server yet....
Auto Ban = false

;; For Player to get banned ( their total VAC Bans => NumberOfVACBans)  AND ( Days Since their Last Ban was <= DaysSinceLastBan)
;; This is also used extDB Protocol VAC:VACBanned returned results

NumberOfVACBans = 1
DaysSinceLastBan = 999999999
BanDuration = 1
;; 0 = Forever, otherwise its x Minutes
BanMessage = Steam VAC Banned

[Log]
;; Flush Logs after each write, more work on Harddrive
Flush = true

[exile]
Type = MySQL
Name = MatthewB2302Exile
Username = user
Password = password
IP = 127.0.0.1
Port = 3306
minSessions = 2
;maxSessions = 4
idleTime = 60
compress = false
; Should only use this if MySQL server is external. Also only for MySQL
Secure Auth = true
; Recommend you turn this on

**Comment by Torndeco** [comment]
You haven't pastebin your extDB2 Log

**Comment by MattDogIRC** [comment]
sorry been gone with wife here
http://pastebin.com/h0XSnj5p

**Comment by Torndeco** [comment]
Either you have multiple extdb-conf.ini  in your A3 Root Directory / @extDB2 / @exileserver directories

Or your first post with extdb-conf.ini  is wrong
extDB2 is complaining the extdb-conf.ini  is missing version info or the version is set to zero.

**Comment by MattDogIRC** [comment]
i definitly dont have extras i only have one in @exileserver and that is my correct file except password username

**Comment by Torndeco** [comment]
Its very basic code... you prob have a typo somewhere
Just grab a new config file & start again

**Comment by MattDogIRC** [comment]
i tried that as u can see from this paste bin
then i edited and it says wrong version even though version is 5 and i never touch it
http://pastebin.com/KGwNcKmk

**Comment by Torndeco** [comment]
It works fine here, maybe you screwed up your file/access permissions.
Which is pretty hard todo for the average user on a windows server.
Also if there was an issue with parsing the ini file, someone would have complained about it over a year ago by now. 

Anyway there is no bug with extDB2 with reading an ini file, afraid its user error

**Comment by MattDogIRC** [comment]
idk what it is that file works perfectly in linux but in windows gives wrong version

**Comment by chris579** [comment]
Do you saved the file in UTF-8 without BOM? I just can recommend to avoid using notepad.exe due to the fact it's saving with BOM every time. Use Notepad++ or a more advanced editor.

**Comment by MattDogIRC** [comment]
it was the damn encoding lol i was useing power shell to edit it was like UCS-2 LE BOM

**Comment by MattDogIRC** [comment]
fixed it :) thanks for help never thought about encoding b4

**Comment by chris579** [comment]
You're welcome. I will expand the wiki with some resolutions for common problems when I'm back home.
