### ISSUE TITLE
Logs are just written when opening them

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#105]
Hey Torneco,

I know, this sounds special but it seems like my extDB logs (the custom ones) are just written when I open them in a Editor.

Let's say I have the server running and flooding it with some entries. If I copy it to another location the log will be empty. If I open it at the same place the log will be full of entries.

I tried it with "FushLogs" option and without.

I don't know If you need a log to check this behaviour. I have debug version but there is no much output for the log option.

**Comment by Torndeco** [comment]
What you describe is just not possible, sounds like OS is caching the empty file when you Ctrl+C it
