### ISSUE TITLE
extDB2: Crash on Fresh install

### ISSUE THREAD

**Issue by Mankeysocks** [Torndeco/extDB2#107]
Fresh install today Arma 3 + sql + altis life crashes on boot.

Could you take alook at my logs extDB2 isnt setup atm useing @ 
was still crashing useing that way i first setup useing that method

http://pastebin.com/Z0xJWiG8 extDB2 Log when crash happened 
http://pastebin.com/14VfgEU9 Arma 3 Rpt log when crash happend

plz thanks sorry

**Comment by Torndeco** [comment]
Redownload extdb2, there was a bugged version of 67.
Use debug version of 67 if it still crashes and send me the log file
