### ISSUE TITLE
Local time is returning utc time

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#108]
As I'm using a german time pattern the local time for me now is 22:11. `9:LOCAL_TIME` returns for me `[1,[2015,12,08,21,11]]`. I'm unsure if this behaviour is willed.

**Comment by Torndeco** [comment]
Yeah its a copy paste error, was off holidays for the last week.
I will look at pushing an update with fix in next day or 2.
Want to update the Poco Library at the same time (using more C11++ features)

**Comment by Torndeco** [comment]
Fixed in v70
