### ISSUE TITLE
 MySQL Error: Unable to locate extDB2 extension!

### ISSUE THREAD

**Issue by MattDogIRC** [Torndeco/extDB2#109]
0:41:14 "ExileServer - MySQL connection error!"
 0:41:14 "ExileServer - Please have a look at @ExileServer/extDB/logs/ to find out what went wrong."
 0:41:14 "ExileServer - MySQL Error: Unable to locate extDB2 extension!"
 0:41:14 "ExileServer - Server will shutdown now :("
 0:41:14 "TCAGame/BIS_fnc_log: [preInit] ExileServer_fnc_preInit (129.002 ms)"
 0:41:14 Connected to Steam servers

windows server 2012
doesn't make log file
all files are were spoused to be 
Useing 

exile mod

**Comment by chris579** [comment]
You didn't read this: https://github.com/Torndeco/extDB2/wiki/Troubleshooting

Please refer to exile forums for support.

**Comment by MattDogIRC** [comment]
oh crap i didn't know he no longer supported it

**Comment by chris579** [comment]
Torndeco never officially supported people having issues with exile. Plus, your issue is related to real dumbness because you didn't read the wiki.

**Comment by Torndeco** [comment]
You need to install vc2015 redist for latest version of extDB2

**Comment by MattDogIRC** [comment]
yes sir that was it thanks very much
