### ISSUE TITLE
Insert into Database issue I am having 

### ISSUE THREAD

**Issue by ace16huey** [Torndeco/extDB2#110]
I am having issues with inserting data into a table. The data is being passed though extDB with no errors showing, but when I put it through the debug version, the output is empty, so I have no idea what I am doing wrong. 

Here is the extDB log:
http://pastebin.com/GgLthNVU

Here is my config: 
http://pastebin.com/afg4uGhP

This is what I am trying to insert:
```sql
_statment = format["INSERT INTO housing (ownerID, houseID, pos, isHouseSelling, houseSellPrice, houseSeller, isOwned) VALUES('%1', '%2', '%3', '0', '0', '0', '1')",_ownerID,_houseID,_pos];
```
I am using the async from the examples folder and currently it is not inserting any values into my database. I may be stupid and just doing soemthign wrong but staring at this for 2 hours isn't helping me much so I guess I should get some help.

**Comment by chris579** [comment]
INSERT never produces any output.

**Comment by ace16huey** [comment]
Well that leads to my next thing, its not doing the inserting. Would there me a reason as to why it is not doing it, but yet no error states to as of why?

**Comment by ace16huey** [comment]
Spent about 3 hours on trying to fix this today, is there a possibility that I did not configure the database correctly? There is nothing in the logs of my database, all tho I am completely new to setting up my own mysql databases and could have messed it up. I would think that there would be an error produced somewhere if that would be so but i may be wrong.

**Comment by Torndeco** [comment]
Nothing wrong with extdb2
Your problem is your sqf code
The protocol id is been passed to extdb2 as 
Code instead as a number

Go to altis life RPG forums for support on their code

**Comment by ace16huey** [comment]
This is not for an altis life server, this is for a custom mission I am currently working on, nor was I saying that anything was wrong with extdb, I was asking to see if I could have sent up my database wrong or something. But alright, I will try and figure it out

**Comment by chris579** [comment]
Use the sample asyncCall.sqf to avoid such errors. You can find it in this repo.

**Comment by ace16huey** [comment]
That is the one I am using, which is why I do not understand why it is not working at the moment.

**Comment by ace16huey** [comment]
Ahh I just looked it over, I looked over my init vs the example init and I did not turn my random number into a string, which would make sense why it is not currently working if that is the case

**Comment by ace16huey** [comment]
I went and I executed my statement actually in the program I use to look at the database and it went in just fine, so I have no idea why the data is not being sent from in the server, It could be that I have an issue with the async, but I do not have the knowledge as to why that is happening.
