### ISSUE TITLE
Support for FreeBSD 10

### ISSUE THREAD

**Issue by killstream** [Torndeco/extDB2#111]
Hello Guys,

Thank you for the awesome job on ExtDB2.

Is it possible to get an build which works with FreeBSD 10?

The current linux(c6) libraries only goto GLIBC 2.12 :(

Thx,
Rat

**Comment by Torndeco** [comment]
There are no plans to make any builds for FreeBSD
ArmaServer Support / Performance for Linux Servers is very poor atm.
So its very unlikely this will ever change.

You can always try to build extDB2 on FreeBSD.
I use a custom version of Poco you can find at https://github.com/Torndeco/poco
Then you need to get dev versions of boost + mysql
Afterwhich you should be able to build extDB2 using CMake

I don't provide support for people doing this due to time issues & people having various degrees of knowledge. But it isn't hard todo on Linux (no idea of FreeBSD.

Note: You will need a x86 build environment, since armaserver is 32bit program  extDB2 needs to be compiled as 32bit aswell.

---------------------------------------------

Its prob just easier to setup a Linux Machine IMO, or for performance reasons (with arma) get a Windows Server.

**Comment by killstream** [comment]
Hello,

Thanks for your kind reply. I installed all the programs under an x86 FreeBSD envirement.

If i get it working, maybe i could be the FreeBSD version provider of extDB2 


With kind regards,

Ton

**Comment by killstream** [comment]
Hello,

Almost could compile it 

Only got this:  extDB2-master/src/abstract_ext.h:97:107: error: no type named 'SessionDataPtr' in 'Poco::Data::SessionPool'  
                        virtual Poco::Data::Session getDBSession_mutexlock(DBConnectionInfo &database, Poco::Data::SessionPool::SessionDataPtr &session_data_ptr)=0;
                                                                                                                                                                                                         ^^^^^^^^^^^^

Using libPocoData.so.30 from poco-devel.

With kind regards,

Ton

From: Torndeco 
Sent: Friday, December 18, 2015 10:53 AM
To: Torndeco/extDB2 
Cc: killstream 
Subject: Re: [extDB2] Support for FreeBSD 10 (#111)

There are no plans to make any builds for FreeBSD
ArmaServer Support / Performance for Linux Servers is very poor atm.
So its very unlikely this will ever change.

You can always try to build extDB2 on FreeBSD.
I use a custom version of Poco you can find at https://github.com/Torndeco/poco
Then you need to get dev versions of boost + mysql
Afterwhich you should be able to build extDB2 using CMake

I don't provide support for people doing this due to time issues & people having various degrees of knowledge. But it isn't hard todo on Linux (no idea of FreeBSD.

Note: You will need a x86 build environment, since armaserver is 32bit program extDB2 needs to be compiled as 32bit aswell.


--------------------------------------------------------------------------------

Its prob just easier to setup a Linux Machine IMO, or for performance reasons (with arma) get a Windows Server.

—
Reply to this email directly or view it on GitHub.

**Comment by Torndeco** [comment]
You can't use offical version of Poco Library
You need to compile a modified version of Poco, since i have altered Poco Session Pool for Database and some more things.
Grab the source at  https://github.com/Torndeco/poco and compile it

**Comment by killstream** [comment]
Hello,

Any chance that you could mail me your custom compiled libraries?

Then i could provide you with the compiled extDB2 for FreeBSD i386.

The original poco-devel compiles with no problems, but the custom one has some issues.

With kinds regards,

Ton

**Comment by Torndeco** [comment]
I have given you the link 3 times now :)
https://github.com/Torndeco/poco
You will need to compile it yourself   gl

**Comment by killstream** [comment]
Hello,

Compiled it.

Got these files:
libPocoCrypto.a
libPocoData.a
libPocoDataMySQL.a
libPocoDataSQLite.a
libPocoFoundation.a
libPocoJSON.a
libPocoNet.a
libPocoNetSSL.a
libPocoUtil.a
libPocoXML.a
libPocoZip.a

Do i need to have shared object files(.so) for extDB2? If so, how do i make them?

//Path to a library.
POCO_Data_LIBRARY:FILEPATH=/usr/local/lib/libPocoData.a
