### ISSUE TITLE
Define column name SQL_CUSTOM_V2

### ISSUE THREAD

**Issue by reaper4231** [Torndeco/extDB2#112]
not an issue, more of a question

is it possible or will it be possible to define a column name in SQL_CUSTOM_V2 like

SQL1_1 = UPDATE table SET ? = 1 WHERE uid = ?;
Number of Inputs = 2
SQL1_INPUTS = 1(the column name), 2(the uid)

**Comment by chris579** [comment]
As mysql recognises the "?" as a param it is not possible to have dynamic column names. You have to make a config entry for every possibility.

**Comment by Torndeco** [comment]
Readup on CUSTOM INPUTS, a3wasteland use them alot.
