### ISSUE TITLE
extBD not working Sp editor session

### ISSUE THREAD

**Issue by Beldum** [Torndeco/extDB2#114]
I'm making a mission file that I plan on running on a server in the future and am having difficulty getting extDB2 working.

It just doesn't seem to be running at all. I used to have extDB running on the editor but I uninstalled ArmA 3 and deleted all data about 6 months ago but recently re-installed it and decided to get back into it.

I did everything required in the Setup for windows (https://github.com/Torndeco/extDB2/wiki/Setup:-Windows)

It returns no error files except "extDB: Error with Database Connection. 1st Scan." in my .rpt

My init.sqf (A code I used to use in extDB 1

VRG_DB_ID = 5678;
VRG_Database_In_Use = false;
[] call {
    _result = "extDB" callExtension "9:DATABASE:VRG_Life";
    if(_result != "[1]") exitWith {diag_log "extDB: Error with Database Connection. 1st Scan.";};

    _result = "extDB" callExtension format["9:ADD:DB_RAW_V2:%1",VRG_DB_ID];
    if(_result != "[1]") exitWith {diag_log "extDB: Error with Database Connection. 2nd Scan.";};
};

My extdb-config.ini SQL part (Rest is still stock)
Also made sure Notepad++ was encoding in UTF-8 without BOM

[VRG_Life]
Type = MySQL
Name = sql4103221

Username = sql4103221
Password = password

IP = sql4.freesqldatabase.com
Port = 3306

;minSessions = 2
idleTime = 60

compress = false
; Really should only use this if MySQL server is external. Also only for MySQL

Secure Auth = true
; Recommend you turn this on  http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html#option_mysql_secure-auth

tbbmalloc.dll located E:\Games\SteamLibrary\steamapps\common\Arma 3
extDB2.dll located E:\Games\SteamLibrary\steamapps\common\Arma 3\@extDB2
extdb-conf.ini located E:\Games\SteamLibrary\steamapps\common\Arma 3\@extDB2

**Comment by Torndeco** [comment]
That code is for extDB, you need to go over the wiki for how  extDB2 works
The extension was renamed because its not back compatiable, its very close

**Comment by Beldum** [comment]
Is it possible to get a copy of extDB 1?

**Comment by Torndeco** [comment]
No sorry i pulled extDB since it has bugs that can cause armaserver to crash

People really should update to extDB2

**Comment by Beldum** [comment]
To easy man, cheers
