### ISSUE TITLE
uiSleep error

### ISSUE THREAD

**Issue by Jormodn** [Torndeco/extDB2#115]
My log see that a connection was opened:

11:41:25 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
11:41:25 "extDB2: Connected to Database"
11:41:26 "extDB2: uiSleep [4]: 85.972"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:26 "extDB2: uiSleep [4]: 85.973"
11:41:40 Game started.
11:41:50 "extDB2: uiSleep [4]: 110.119"
11:41:50 "extDB2: uiSleep [4]: 110.119"

But the database sill empty, no new player or somthing.
I use it for AltisLife 4.3

**Comment by chris579** [comment]
This issue is related to Altis Life code, however the sleep in the locked state is missing in asynccall.sqf

Btw: never heard about version 4.3 seems to be a buggy version

**Comment by chris579** [comment]
Just had a look at the code, somebody removed the sleep statement. I still recommend to use 3.1.4.8 since it is still the far best version.
