### ISSUE TITLE
MISC RANDOM_UNIQUE_STRING How to

### ISSUE THREAD

**Issue by Aloee** [Torndeco/extDB2#117]
extDB2 Ver. 62
How to use RANDOM_UNIQUE_STRING option in MISC protocol ?
Doing:
`_result = call compile ("extDB2" callExtension "0:misc:RANDOM_UNIQUE_STRING");`

Log:

> extDB2: Extension Input from Server: 0:misc:RANDOM_UNIQUE_STRING
> extDB2: Extension Output to Server: [0,"Error Syntax"]

Maybe need pass some parameter, something like the number of characters?
But (0:misc:RANDOM_UNIQUE_STRING:10) return the same.

**Comment by Torndeco** [comment]
For starters the version is to old for support
v70 = latest

Second you need to add the protocol first
Read 
https://github.com/Torndeco/extDB2/wiki/Calls:-Setup

**Comment by Aloee** [comment]
Thank you ! Yes protocol added )
