### ISSUE TITLE
Server objects all of a sudden not loading

### ISSUE THREAD

**Issue by hobart666** [Torndeco/extDB2#118]
Hi I run a version of a3wasteland and I did some windows updates (not sure if the reason) but after I restarted my server and I now get this in my .rpt.

`2016/02/13, 16:28:30 File mpmissions\__cur_mp.Altis\persistence\server\setup\extDB\async_database.sqf, line 63
2016/02/13, 16:28:30 Error in expression <

_objects pushBack _objData;
} forEach _result;

_objects
>
2016/02/13, 16:28:30   Error position: <_result;

_objects
>
2016/02/13, 16:28:30   Error Undefined variable in expression: _result
2016/02/13, 16:28:30 File mpmissions\__cur_mp.Altis\persistence\server\world\extDB\getObjects.sqf, line 60
2016/02/13, 16:28:30 "Creating territory capture trigger for 'TERRITORY_0_KAVALA_A'"
2016/02/13, 16:28:30 "Creating territory capture trigger for 'TERRITORY_0_KAVALA_C'"
2016/02/13, 16:28:30 "Creating territory capture trigger for 'TERRITORY_1_ALTISAIR_A'"
2016/02/13, 16:28:30 "Creating territory capture trigger for 'TERRITORY_1_ALTISAIR_B'"
2016/02/13, 16:28:30 "Creating territory capture trigger for 'TERRITORY_1_ALTISAIR_C'"
2016/02/13, 16:28:30 "WARNING: No config_territory_markers definition for marker 'TERRITORY_IRAKLIA_RUINS_1'. Deleting it!"
2016/02/13, 16:28:31 "A3Wasteland - world persistence loaded 0 objects from extDB` If you can help that woud be great if not I understand as well.

**Comment by chris579** [comment]
That's related to wasteland code and not to extDB. Contact the a3wasteland team to get support.
