### ISSUE TITLE
Can't connect to local MySQL server through socket '/tmp/mysql.sock'

### ISSUE THREAD

**Issue by Locknlol** [Torndeco/extDB2#119]
I'm attempting to run Altis Life and they told me "these aren't altis life issues" and directed me here; so I'm curious why I'm getting this issue.

```
[00:54:50 --5:00] [Thread 5043] extDB2: Database Type: MySQL
[00:54:50 --5:00] [Thread 5043] extDB2: Database Exception Error: Connection attempt failed: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
 0:54:50 "extDB2: Error with Database Connection"
```

Currently running on Ubuntu 14.04 using
- Altis Life v4.4
- extDB2 70

```
[ArmaLife]
Type = MySQL
Name = AltisLife

Username = AltisLife
Password = randompassword

IP = 127.0.0.1
Port = 3306
```

**Comment by Torndeco** [comment]
The logs are pretty much telling you your issue
Its not able to connect to  /tmp/mysql.sock

Sidenote: MySQL uses sockets for local connections on Linux for performance reasons.

Check your MySQL Server is actually running local on your machine & is setup correctly

**Comment by Locknlol** [comment]
Definitely, I am running mysql on both servers i'm attempting to run this on, however my install of MySQL according to /etc/mysql/mysql.conf.d/mysqld.cnf

"socket          = /var/run/mysqld/mysqld.sock"

I'll continue digging around I guess. Thanks though.
