### ISSUE TITLE
Unable to query a TIMESTAMP column

### ISSUE THREAD

**Issue by KBW1994** [Torndeco/extDB2#120]
Hello, I know that colons are an illegal character in the database. Cells which simply log the timestamp in date/time format in a cell to show when a record was inserted/updated therefore cannot be queried due to automatically having colons therein.

I am posting this as a question to see if there is a workaround for this. I ran a search/replace query to attempt to replace colons with some other character, however it returned 0 rows effected.

Syntax was like

UPDATE YourTable
SET Column1 = REPLACE(Column1,':',';')

**Comment by chris579** [comment]
You can't query timestamps. This is related to poco. You should convert the timestamp into a string to select it. This can be done directly in the query.
