### ISSUE TITLE
extDB2.dll dependencies

### ISSUE THREAD

**Issue by hobart666** [Torndeco/extDB2#121]
Hi, Im trying to upgrade to the pack Agent rev has posted here https://github.com/A3Wasteland/Release_Files and Ican get the server to connect to the db with the new .dll with the old libraries it connects but I'm having the destroyed vehicles re-spawning problem with that one. Anyhoo I'm using a game host co. and would like to know what run-times/dependencies  this needs so I can ask them to install them for me. 
Thank you!

**Comment by Torndeco** [comment]
Latest extDB2 requires vc2015 x86 to be installed...
If it connects to the database fine, sounds like an sqf error in your mission

**Comment by hobart666** [comment]
Thank you, and at the beginning of my sentence I meant can't get the server to connect with the latest .dll :)
