### ISSUE TITLE
Unable to retrieve data from JSON column

### ISSUE THREAD

**Issue by Nesias** [Torndeco/extDB2#122]
While im able to insert data into a column with JSON as data type.
Im unable to retrieve data form that column.

The sqf code that i use to insert data is like this: 
`query = format ["INSERT INTO test (data_in) VALUES ('%1');", [1,2,3, "123"]];
data = [ query, 1] call xxx_fnc_async;`

If i use any of the following codes im not able to retrieve any data: 
`query = "SELECT * FROM test;"; data = [ query, 2] call xxx_fnc_async;`
`query = "SELECT data_in FROM test;"; data = [ query, 2] call xxx_fnc_async;` 

The following one results in an CTD of ARMA 3 with an Access Violation Error code:
`query = "SELECT cast(data_in as char) FROM test;"; data = [ query, 2] call markets_fnc_async;`

Every try to retrieve data (except the CTD one) creates the following entry in the log file:
`[16:14:30:282640 +02:00] [Thread 6656] extDB2: SQL_RAW_V2: Error StatementException: MySQL: [MySQL]: unknown field type`

Is this because JSON is not supported by extDB?

**Comment by Torndeco** [comment]
MySQL Json Datatype is not supported.

The CTD is odd
If you can trigger it using a supported datatype
I would be interesting in extDB2 debug logs & database snapshot so i can replicate it

**Comment by Nesias** [comment]
Ah okay, thats why i was unable to get any data. 
If you ever consider to support it, it would be a nice way to store Arrays, like the "Altis Life"-license ones.

Regarding the CTD, im not sure if i can trigger it with another datatype. 
So far, it only happend when i tried to access the JSON column, using cast. 
If it happens with another datatype i will report it.
( The DB is almost empty, with only 2 other tables that i use for a project im working on.)

**Comment by Torndeco** [comment]
Its very unlikely to be supported anytime soon

----------

The DB Snapshot is save myself some time etc in replicating the issue.
Plus sometimes the crash is due to factors i.e datatypes the person hasn't mentioned
So basically i want the logs & DB Snapshot before i even loot at the issue

**Comment by Nesias** [comment]
Just tested the cast command by casting int() and varchar() data into char. 
No CTD, no problems at all.
