### ISSUE TITLE
Re-defining protocol

### ISSUE THREAD

**Issue by Spackenbremse** [Torndeco/extDB2#124]
Hello,

we've been using extDB2 for quite a while in our mod now. It is a persistent database which is being loaded with every mission.

Now here comes the big issue. Whenever we're running a mission using extDB2 and change it to another mission using your plugin (using #mission), the connection will fail to initialize. Following is to be found in the logs:

[21:24:30:489649 +02:00] [Thread 1232] extDB2: Already Connected to a Database
[21:24:30:489685 +02:00] [Thread 1232] extDB2: Error Protocol Name Already Taken: SQL

Now, I completely understand the issue here: we are trying to re-define the protocol using ADD_DATABASE_PROTOCOL. 
Is there a command to either close a connection in order to re-open it later or a possibility to enable re-defining a protocol using the same name (like in case you siwtch missions using the #mission command)?

**Comment by Torndeco** [comment]
Nope this is a design choice.

Basically once setup and locked its not possible to undo or add more protocols.
This is to help secure database against hackers that remote code execute.
Also it's not possible to make setup stage of extdb2 threads are without it effect performance by using more mutex locks.


Basically you need to setup extdb2 for all your missions at once.

**Comment by ACyprus** [comment]
Hello chaps

Whilst I understand the security concerns, if this functionality ever becomes a more requested feature I'd like to add my vote for it.

I'm currently handling the error but would be nice to perform a graceful shutdown of the connection or protocol.

Many thanks for such a great extension, @Torndeco - our campaign ops would be difficult without it. :+1:

**Comment by Aloee** [comment]
You just can save protocol identifiers in [uiNamespace](https://community.bistudio.com/wiki/uiNamespace) variable, on initialization check: if is set - to use, else make a new connection

**Comment by chris579** [comment]
You should make a general server addon initializing your extDB2 once. After the initialization you can set the protocol id as an uiNamespace variable to get it when the next mission starts.

Example:

```
if(!isNil {uiNamespace getVariable "extDB_dbID"}) then
{

	// Initialize extDB here
	extDB_ID = "myID";

	uiNamespace setVariable ["extDB_dbID", <id>]; // Insert your custom id for <id> here
}
else
{
	extDB_ID = uiNamespace getVariable "extDB_dbID";
	// extDB is already initialized
	diag_log format["extDB was already initialized! ID: %1", extDB_ID];
};

// extDB_ID can be used for MySQL queries now
```
