### ISSUE TITLE
Random server crash

### ISSUE THREAD

**Issue by hobart666** [Torndeco/extDB2#126]
Hi I have an altis server and Chernarus server both using extdb2 and the altis one runs well no real issues at the moment but Im getting random crashes on the chernarus one with this at the end of the .rpt:
 Extensions:
  extDB2 (.\extDB2.dll) [64.0.0.0] [64.0.0.0]
Distribution: 0
Version 1.56.134627
Fault time: 2016/03/25 19:49:39
Fault address:  6B0FE304 01:0000D304 C:\TCAFiles\Users\JoshuaL3\6406\extDB2.dll
file:     A3Wasteland_v1.2 (__cur_mp)
world:    Chernarus
Prev. code bytes: 00 00 8B E9 89 7C 24 14 C1 ED 05 83 E1 1F D3 E0
Fault code bytes: 31 04 AF 75 38 B8 01 00 00 00 39 42 04 76 2E 8D

Registers:
EAX:00000001 EBX:3BC3100C
ECX:00000000 EDX:6B7216EC
ESI:FFFFFFE0 EDI:3BC3100C
CS:EIP:0023:6B0FE304
SS:ESP:002B:02A36AA8  EBP:07FFFFFF
DS:002B  ES:002B  FS:0053  GS:002B
Flags:00210246
=======================================================
note: Minidump has been generated into the file A3DS\arma3server_2016-03-25_19-19-19.mdmp 

Any insight would be great both copies of my extdb2 files mirror each other between servers and as I stated the altis one doesn't get this issue.

**Comment by Torndeco** [comment]
Dump logs are only useful for arma

I need full RPT & extDB2 Log from a crash

**Comment by Torndeco** [comment]
64 Version is a bad version

It is no longer available to download from a3wasteland or this repo

**Comment by hobart666** [comment]
For some reason I cannot get the newer ones to load even with a new
iteration of the db.

Joshua Lee
603-913-3265

**Comment by Torndeco** [comment]
Newer ones require VC2015 redist  32bit version

**Comment by hobart666** [comment]
thank you sir, will give that a shot.

Joshua Lee
603-913-3265

**Comment by hobart666** [comment]
OK, tried that as well no joy. it just acts as if I have no extDB2.dll in
there at all and I'm using fresh everything from AgentRev's release files
master.

Joshua Lee
603-913-3265

**Comment by Torndeco** [comment]
Latest extDB2 requires vc2015 32bit version, after that check you don't have the dlls blocked and tbbmalloc in the arma3 root directory.
There is no other reason it shouldn't work...

But you should  go to AgentRev for support then, as i have no clue what version you are running etc...

**Comment by hobart666** [comment]
Blocked? Ok thank you for all the insight. What do you mean blocked? if i
use the old version that you said is outdated it runs, but the newest
version I can get doesn't but I have set noting to block it. Sorry for my
n00bish questions.

Joshua Lee
603-913-3265

**Comment by chris579** [comment]
Blocked means blocked by the system. By default the system is blocking .dll and .exe meaning the prevention of any execution or loading. Therefore you have to right click on the dlls and go to Properties and then click on Unblock.

For newer versions of extDB 2 you need Visual C++ Runtime 2015 because the C++ library was updated from older 2013 to latest 2015. Also you have to download the 32bit version as Arma runs in 32 bit. I think this is the point you're missing.
