### ISSUE TITLE
Unable to properly save characters in UTF-8 (like accent)

### ISSUE THREAD

**Issue by LzpHiro** [Torndeco/extDB2#128]
Hi, 

We are a french team working on a Arma3 Server,so we frequently use accentuated characters as it's part of the french language. So whenever we try to save something like 'Pêche', it's saved in the database as 'PÃªche'. 

I looked into the configs and did not find any options to enable UTF-8 support in ext-db, so I am pretty confident that this has yet to be implemented.

So yeah, I would like to know if you could do something to support UTF-8 in the near future or if you have an already avaible fix.

**Comment by Torndeco** [comment]
Make up a small repo and don't forget to send sql to create database
And i will look into it when i get a chance.

Need to check its not Arma / Database Scheme causing the issue...
But really shouldn't be any issues with extDB2 itself
