### ISSUE TITLE
extDB2 v63 Release

### ISSUE THREAD

**Issue by AryxRayx** [Torndeco/extDB2#129]
Is it possible to download the Release files for v63 anywhere?

**Comment by chris579** [comment]
Is it possible to search for it for more than only 290 seconds?

However, here you are:
https://github.com/Torndeco/extDB2/archive/63.zip

**Comment by Torndeco** [comment]
I don't keep old versions up forever.
Due to bugs & people running older versions.
That then go complain to BIS about server crashes

The version you are requesting is over a year old
