### ISSUE TITLE
ARMA3 can't reach extDB

### ISSUE THREAD

**Issue by SINE** [Torndeco/extDB2#14]
My ARMA3 dedicated can't reach the extension, it sends the call and then doesn't proceed any further (doesn't get an answer, whole server is stopped at that point).

The extension is loaded properly as was extDB, I just added the 2 after the name in the startup properties.

The server log part that tells its loaded:
17:21:17                                            @extDB2 |              @extDB2 |      false |             GAME DIR | da39a3ee5e6b4b0d3255bfef95601890afd80709 | C:\Gameserver\ArmA3\A3Master_Test1\@extDB2

SQF code:
[] spawn {
	private["_result"];
	diag_log "extDB2: version check follows";
	_result = "extDB2" callExtension "9:VERSION";
	diag_log format ["extDB2: version: %1", _result];
};

--

extDB doesn't tell that anything reached it in the log (it is completely empty).
Using version 45 of extdb2.
Using extdb-test.exe the call "9:VERSION" works fine.

------
EDIT:
After using the DEBUG Version nothing changed, the log remains empty.

**Comment by Torndeco** [comment]
Just use Version 44 for now
Until i get a chance to check what the issue is, its prob due to logging changes in v45
Arma patch day so gonna give it some time till i go update dev server etc...

**Comment by SINE** [comment]
If you're getting any issues with the new arma server version, just download the server not through cmd but through steam directly, it has a bug atm.
I will test v44

**Comment by Torndeco** [comment]
Linux Server has no GUI, so has to use CMD
Last i heard on Skype it crashes with new update...

Regardless its alot easier to wait for BIS to push out a fix. 
Than messing around with workarounds.

**Comment by SINE** [comment]
Just upload from your local ARMA3 installation the 2 files
kart/Addons/anims_f_kart.pbo
heli/Addons/cargoposes_f_heli.ebo

**Comment by SINE** [comment]
Just upload from your local ARMA3 installation the 2 files
kart/Addons/anims_f_kart.pbo
heli/Addons/cargoposes_f_heli.ebo

**Comment by SINE** [comment]
They brought out a fix for the servers

**Comment by Torndeco** [comment]
Fixed v46

**Comment by SINE** [comment]
thanks :+1:

**Comment by Torndeco** [comment]
Forgot to hit publish on the Release...
Opps v46 is available now
