### ISSUE TITLE
init_remote.sqf

### ISSUE THREAD

**Issue by killerty69** [Torndeco/extDB2#16]
Line 22 : Missing semi-colon
Line 44: Mission semi-colon

Parse function requires that the _result data be converted into an array because it can be processed because callExtension returns a string. 

Possible fix: 
Use toArray() to convert string into array and look for location of the colon (unicode value 58)
if (_x isEqualTo 58) 
Then separate into two arrays and call "toString" on both and "parseNumber" on _clientID after

I have the code working, but it is very messy at this time. I can do a pull request if you would like or you can fix it.

**Comment by Torndeco** [comment]
Yeah its still just WIP Code, untested
Really just a rough guide for people

toArray is overkill imo.
Only need to parse the start of string to fetch clientID or uniqueID to fetch multi-part message.
Its possible todo it using select, just i got the syntax wrong for calling it.

Gets abit confusing when you switch from c++ / sqf / python
Need to benchmark select method versus toArray, i eventually get around to it.
But more than likely the select method is faster.


No point to ParseNumber
You will just convert the string -> int, so you can convert int->string when sending to callExtension.
Plus there is no guarantee, uniqueID will always be an integer.

**Comment by killerty69** [comment]
True, not even sure why I said parseNumber on _clientID as it will be converted to scientific notation and that will mess up the call back either way. 

 I agree it is overkill, but it was just one possible quick way of getting it up an running. Sqf has very little built in string manipulation for parsing data which is why I suggested it, of course it is possible though. 

I will clean up my code and post it tomorrow with the toArray and string parse method if you would like me to.

**Comment by killerty69** [comment]
Nevermind, I see you have already update it. I will test it out tomorrow and let you know if there are any problems.
