### ISSUE TITLE
SELECT * failure (unknown field type)

### ISSUE THREAD

**Issue by kkotowick** [Torndeco/extDB2#17]
extDB2 seems to be unable to handle the * operator, either in RAW or CUSTOM. For example,

    2:protocol_name:SELECT * FROM players

returns with "SQL_RAW: Error StatementException: MySQL: [MySQL]: unknown field type". If specific columns are specified, however, it works fine, such as:

    2:protocol_name:SELECT name FROM players

Is this a known issue? The * operator is rather important, I think.

**Comment by Torndeco** [comment]
SELECT * works fine

The error says unknown field type i.e
One of the datatype for column / field is not supported

**Comment by kkotowick** [comment]
Yep, that's it. Thanks!

**Comment by nerkaid** [comment]
DATETIME is acepted, TIMESTAMP no.
