### ISSUE TITLE
Stored procedures not returning full result

### ISSUE THREAD

**Issue by kkotowick** [Torndeco/extDB2#19]
I have a stored procedure in my database, with the following definition:

    CREATE PROCEDURE `test`(IN 'ID' VARCHAR(50)) 
	NO SQL
    BEGIN
    	SELECT name, lastconnect FROM players WHERE playerid = ID;
    END

If I call the procedure directly from the database (using PHPMyAdmin, in my case):

    CALL test('12345')

Then it returns a result with a single row and two columns, holding the player's name and a datetime (i.e. the correct response):

    myname   |   2015-03-06 23:49:24

 However, when I call that same code through extDB2, it returns

    [1,[]]

Which obviously isn't the result I need. Using "OUT" variables in the procedure isn't an option either, because the real procedure has far more than 2 return columns.

**Comment by Torndeco** [comment]
Think i have solution i just need to recompile some stuff + test out a fix.
But need to get some sleep first, might be ready later today or tomorrow.

Meantime you could always use SQL_CUSTOM, it basically uses Prepared Statements for similar effect which it caches the session to reuse the prepared statement etc..

If you can next time, 
Try to make up SQL Commands to create the table etc 
Saves me time trying to replicate / learn sql commands i.e i don't use Procedures much myself.
Just saves me abit of time

**Comment by kkotowick** [comment]
Yeah, I'll have a full SQL export next time. Thanks for getting to these things so quickly!

**Comment by kkotowick** [comment]
On that note though, might you be able to add some documentation on the prepared statements? For example, what is the first 'one' for in "SQL1_1"? For multiple-line statements, the second 'one' changes ("SQL1_2"), but what does the first one signify?

**Comment by Torndeco** [comment]
SQL1_1
SQL1_2
etc
Is so you can split up a single statement into multiple lines to make it easier to read
i.e like  https://github.com/BAROD/Koth_Kavala/blob/master/extDB2/sql_custom/koth.ini#L42-L50

SQL2_x is for the 2nd statement to run
That way you can run multiple statements from a single callExtension.

Note: Only returns result set from the last statement.

**Comment by Aeneas1** [comment]
try "Select test('12345')", so it works for me

**Comment by Aeneas1** [comment]
and of course you have to use extDB modus 2

**Comment by kkotowick** [comment]
Your suggestion will work if you create it as a function, but not if you create it as a procedure. Procedures can not be called from within a statement, functions can.

**Comment by Torndeco** [comment]
Right after some more looking at issue, will take longer to implement
Have no idea on time frame for completion, since will require abit of work todo it correctly

**Comment by kkotowick** [comment]
In the mean time, is it possible to use a given input several times in a SQL_CUSTOM prepared statement? For example:

    [getPlayer]
    SQL1_1 = CALL getPlayer(?,?)
    SQL2_1 = SELECT* FROM players  WHERE playerid = ?
    Number of Inputs = 2
    SQL1_INPUTS = 1,2,1
    OUTPUT = 1

There are three '?' for inputs, but I want to use the first input twice (for the first and third question marks). If this isn't possible currently (and it doesn't seem to be, it keeps throwing an error), could it be added?

I also tried setting a variable so that I could use it multiple times:

    [getPlayer]
    SQL1_1 = SET @playerID = ?
    SQL2_1 = CALL getPlayer(@playerID,?)
    SQL3_1 = SELECT* FROM players  WHERE playerid = @playerID
    Number of Inputs = 2
    SQL1_INPUTS = 1,2
    OUTPUT = 1

But that throws and error "wrong bind parameters count".

**Comment by Torndeco** [comment]
[getPlayer]
SQL1_1 = CALL getPlayer(?,?)
SQL2_1 = SELECT* FROM players  WHERE playerid = ?
Number of Inputs = 2
SQL1_INPUTS = 1,2,1
OUTPUT = 1

change to

[getPlayer]
SQL1_1 = CALL getPlayer(?,?)
SQL2_1 = SELECT* FROM players  WHERE playerid = ?
Number of Inputs = 2
SQL1_INPUTS = 1,2
SQL2_INPUTS = 1
OUTPUT = 1

**Comment by Torndeco** [comment]
Closing issue....

There is a nice bit of work to writing MySQL code for handling + exception handling for Procedures + retrieving the results. 

Especially when the current code (from Poco Library) supports  SQLite + ODBC (if i enable it) nicely.
Don't feel like its worth it the time adding it in, especially when SQL_CUSTOM can fill in the role nicely.

Am going to spend time on working on other parts for extDB2 / other projects instead.

**Comment by kkotowick** [comment]
I'd like to note that there is another issue which I think is closely related. If you try to call two stored procedures from within a single prepared statement, it throws an error 2014 (commands out of sync). This, I believe, is because stored procedures can return multiple result sets and get unhappy if you try to call another without iterating through all the result sets received from the previous one first.
