### ISSUE TITLE
Support for "AltisLifeRPG-Arrays"

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#28]
I think the "altisliferpg-arrays" are not further supported by extdb2, are they? If not, it would be awesome to add the support for them, furthermore that would allow to upgrade the whole AltisLife thing to the new extDB "level" :penguin:

**Comment by Torndeco** [comment]
https://github.com/Torndeco/extDB2/wiki/Changes-from-extDB

Basically altisliferpg-arrays option was never needed... 
It will still compile fine, with the single quotes around.
https://community.bistudio.com/wiki/String

The only possible use if you were using SQL_RAW + SQL_CUSTOM at the same time, which would be just crazy.
