### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Colonelfury** [Torndeco/extDB2#29]
I am trying to use this for my altis life server and am having a problem. No matter what I do the only thing that happens with ExtDB2 is that it says "Creating Worker Thread +1" over and over in the logs. I have tried with a fresh install of our server to make sure that it was not the problem, and it is still happening. The RTP does not show any errors either and I am wondering if you know a possibly fix. Thanks!

**Comment by Torndeco** [comment]
In future please include logfile from debug version of extDB2
Also RPT logs  / sql_custom file aswell if appropriate
It allows me to see what going on alot faster..
You have given zero useful info for me to work on

-------

Anyway
extDB  =  "Creating Worker Thread +1"
extDB2 =  "extDB2: Detected {0} Cores, Setting up {1} Worker Threads"

From your comment you are still using extDB + not extDB2
extDB is no longer supported...
