### ISSUE TITLE
Update Redis Code

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extDB2#3]
Add exception handling + ability to reconnect to redis server
Add support for AUTH via extdb-conf.ini file

Add SYNC support, only ASYNC supported atm

**Comment by Torndeco** [comment]
Redis Status left todo is

Add code to resolve Address, atm its takes IP Address
Catch exceptions thrown by Redis Code i.e when connection is lost etc
Saving results to 2:<Unique ID>

**Comment by nerdalertdk** [comment]
Uhh can't watt for this :)

**Comment by Torndeco** [comment]
Unless there is an actually public available mod that will make use of Redis (Epoch A3 doesn't count).
I will most likely be pulling Redis from extDB2.

**Comment by chris579** [comment]
Yuka said something about adding it to AltisLife, dunno if it's true. Also I'm interested to it, but I need an example how to use it properly.

**Comment by nerdalertdk** [comment]
I Might change our king of the hill kill log to use redis so the sql only handles load and save xp/gear
