### ISSUE TITLE
AltisLifeRPG_Array support

### ISSUE THREAD

**Issue by ithr0n** [Torndeco/extDB2#34]
Hello,

why did you drop support for output type AltisLifeRPG_Array?
Which output type should I use instead (String? Nothing?)

Regards

**Comment by BAROD** [comment]
https://github.com/Torndeco/extDB2/issues/28#issuecomment-84337713

**Comment by Torndeco** [comment]
Yeah just use nothing, was never needed...
Also https://github.com/Torndeco/extDB2/wiki/Changes-from-extDB
