### ISSUE TITLE
Revert back to extDB behaviour when SQL Result is Empty

### ISSUE THREAD

**Issue by ithr0n** [Torndeco/extDB2#35]
When using the provided example code and the database will return something like "[[]]" the code file is returning exactly this array. In extDB it returned just "[]". All my checks are now failing.

I suggest to change the very last lines of the file to:

```
if(!_multiarr) then {
    _return = _return select 0;
} else {
    if (count(_return select 0) == 0) then { _return = []; };
};

_return;
```

Is it a good idea? Why did you change the behavior?

**Comment by Torndeco** [comment]
Nah thats horrible todo that in SQF code, you are creating extra work for armaserver todo.
Will be fixed in SQL_CUSTOM_V2 + SQL_RAW_V2 whenever next version is released

**Comment by m3talstorm** [comment]
Don't think doing a count on an array is very taxing for the server ;)

**Comment by Torndeco** [comment]
Depends if arma arrays keep an internal count in the code or if it counts the array size when its called
ie. Using isEqual to compare the string might be a faster method.

Regardless its still better to fix the behaviour in the extension than in sqf code.
Will be new version of Protocols so it wont break anyones code...

**Comment by m3talstorm** [comment]
I would hope so...but you never know with Arma.

**Comment by Torndeco** [comment]
Well i changed my mind after sleeping on it :)
Will be leaving the current behaviour in, as it makes more sense and avoids breaking anyones extDB2 code.

extDB returned [1,[[]]]   if there no result.
extDB2 returns [1,[]] if there is no result.

The second method makes more alot more sense logically.
Anyway if your SQL Query has a chance of returning an empty result, you should be calling fn_async + returning multiarray results
Then you can add SQF logic to check the result if its empty

_result = [_query,2,true] call fn_async;
if (count _result) = 0 then {....} else {....};

**Comment by ithr0n** [comment]
Sorry, I'm a little bit confused... While logging outputs from my sqf code, I get a result from extDB2 with [[]]. When doing a count on this array, it is returning 1 ( count([[]]) == 1).

When moving Altis Life to extDB2 there are some cases where the sqf code is broken, because of this behavior. What should I do to fix this? Use my suggested code? Do other changes to fn_async.sqf? Change the check of a result in my specific sqf code?

Could you provide a more detailed example for this issue?

**Comment by Torndeco** [comment]
Next time please send a debug extDB2 log output its alot clearer.
Will fix in next version via SQL_RAW_V2 + SQL_CUSTOM_V2

I was under impression
extDB2 -> [1,[] ]
extDB -> [1,[[]] ]
When it is the other way around

**Comment by Torndeco** [comment]
kk fixed in v50 of extDB2.
Use SQL_RAW_V2 / SQL_CUSTOM_V2

**Comment by ithr0n** [comment]
Hey,

I'm back on topic now and trying to use extDB2 for my Altis Life 4.0 server.. when using your example code I got an issue with a SELECT statement:

SELECT wantedName FROM wanted WHERE wantedID=?;

When executing this and there is no result data, extDB2 returns [1, []]
- as expected

When there is data, the result data is: [1, [["ExampleName"]]]
- this is why I'm confused again

Again, my SQF code fails with fn_async.sqf, because I'm calling the method from SQF by this:
```
wantedCheck = format["wantedFetchName:%1",_uid];
waitUntil{!DB_Async_Active};
_wantedQuery = [_wantedCheck,2] call DB_fnc_asyncCall;
```

This is necessary since the data returning is a multiarray.. But when no data is available, it is returning the data as single array (which was the extDB behavior and is good for reason I think).

What would you suggest? Check the return value in fn_async.sqf when having multiarray = true if there is really data available (for example via count(_queryResult select 1) ... ?)

**Comment by Torndeco** [comment]
When there is data, the result data is: [1, [["ExampleName"]]]
    this is why I'm confused again
------------
This is because your result could contain 1 row or 100+ rows.
Its alot easier to problem in sqf if its always a nested array, otherwise it would be a pain to figure out if its a multi-row result or single-row result.

------
Yes for multi-row result just use multiarray=true & do a count check or  isEqualTo [].

**Comment by ithr0n** [comment]
But when always a multi-array is returning... then why is extDB2 returning [1, []] for empty results?

So I have to call always with multiarray = true and do the check in my sqf file... Because when I do not and the query does not get any data from the data source, the sqf script will fail.

**Comment by Torndeco** [comment]
Seriously ?
This was changes months + months ago, it is up to update your sqf code / sql queries etc...
This is the same behaviour as extDB, it was just broken in extDB2 for awhile + no-one reported it.
Will not be reverting this change

--------------------

[]  = No result
[[result]] = Single Row result
[[result_1],[result_2],[result_3]]   = Multi Row Results

Where x is an array of result

**Comment by chris579** [comment]
Your issue is related to your asyncCall file and not to extDB. You can use the same asyncCall file yuka provides with 4.0 when using DB_Custom_v2.

**Comment by ithr0n** [comment]
I don't think so, Chris. I had many server sided script errors.

I reverted the asyncCall file back to the original one, and there are many points I need to adjust to avoid script errors when an empty result is received.

But it's now working for me, my post was just to get a clear statement about the using from Torndeco.

**Comment by chris579** [comment]
Then you're doing it wrong. Dunno why u need a official statement confirming you have to use v2 instead of v1. That's your problem at all.
