### ISSUE TITLE
fred41 tbbmalloc support

### ISSUE THREAD

**Issue by ithr0n** [Torndeco/extDB2#36]
Sorry that I open an issue item for that, but don't know how to ask for this in any other way...

Your extDB did not support tbbmalloc of fred41.. Is it supported with extDB2 or do I have to follow the same procedure as for extDB?

Did not find anything about this in the wiki or older issues.

**Comment by Torndeco** [comment]
fred41 malloc isn't updated anymore
But yeah if you are still using it, you need to renamed the fred41 dll's like before.
