### ISSUE TITLE
SQL_RAW_v2 not working

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#40]
![alt tag](http://i.gyazo.com/6ecfed1ad7f2fbb1bba411a918508e62.png)

As seen on the screenshot, the SQL_RAW_v2 is not working, same for trying to add the protocol without "ADD_QUOTES". Also the connection works properly with SQL_RAW

**Comment by Torndeco** [comment]
Works fine just tested again here with windows test application.

Please send logs files next time, as i cant verify what version of test program you are using there

**Comment by Torndeco** [comment]
Your problem is  you typed
Load Database = ALtisLife
Add Database Protocol = AltisLife

Its case sensitive for Database names + Protocol names

**Comment by chris579** [comment]
Fuck, sorry, missed it, checked it some times but didn't saw it :dancers:
