### ISSUE TITLE
Unable to get file version size

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#43]
Unable to get file version size: [PATH]\@extDB2\extDB2.dll

This is in the rpt log....

**Comment by Torndeco** [comment]
Just ignore it...

BIS adding extra debug info to RPT Logs, its just complaining it can't get version info from the dll.
Its a windows only feature so i have no plans on implementing it.

extDB2 version info is available via 9:VERSION or extDB2 logfiles.
