### ISSUE TITLE
LOCK_STATUS values are wrong

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#44]
Wiki:
System Command - LOCK_STATUS
"extDB2" callExtension "9:LOCK_STATUS"
Returns [1] if extension is unlocked.
Returns [0] if extension is locked.

Here a little debug:
"extDB2: Lock1: 0" -> unlocked
"extDB2: Locked database"
"extDB2: Lock2: 1" -> locked

The wiki seams wrong ;D

**Comment by Torndeco** [comment]
fixed + thanks
