### ISSUE TITLE
STEAM bans return

### ISSUE THREAD

**Issue by nerdalertdk** [Torndeco/extDB2#47]
Hi,

I'm trying to check if an player is VAC banned when he join the server.
I don't understand the return I get from this code.

```cpp
private ["_player","_playerUID","_playername","_return"];
_player 	= [_this, 0, objNull, [objNull]] call BIS_fnc_param;
_playerUID 	= getPlayerUID _player;
_playername	= name _player;
_return = true;


_result = call compile ("extDB2" callExtension format["2:steam:STEAMBanned:%1",_playerUID]);
if (_result select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error STEAM: %1", _result]; false};

diag_log format["CSG: %1",_result]; // 
_return
```
im getting this in the RPT

2015/04/29, 11:18:49 "CSG: [2,"9816"]"

**Comment by nerdalertdk** [comment]
my fn_extdb.sqf

```cpp
// STEAM
	//
	//_result = call compile ("extDB2" callExtension "9:START_STEAM");
	//if (_result select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error START_STEAM: %1", _result]; false};
// This is returning an error
// 2015/04/29, 11:33:19 "extDB2: Error START_STEAM: [0,"Error Invalid Format"]"

	
	_result = call compile ("extDB2" callExtension "9:ADD_PROTOCOL:STEAM:steam");
	if (_result select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error ADD_PROTOCOL:STEAM: %1", _result]; false};
	diag_log "extDB2: Connected to STEAM";
```

**Comment by Torndeco** [comment]
0: SYNC Mode (supported in STEAM Protocol)
1: ASYNC
2: ASYNC + Return Value

So 2:steam:STEAMBanned:%1 is returning the unique id to fetch the result
So "9816" = the unique id, just use fn_async to handle fetching the VAC Ban Results etc...

Alternatives is just use 1:ASYNC + let the extension do automatic RCon Bans, assuming you got rcon setup correctly
Or you can alter your SQL_CUSTOM file to the same aswell

**Comment by nerdalertdk** [comment]
Hi Again

well i'm just testing it out, so an 
```_data = [format["2:steam:STEAMBanned:%1", _playerUID], 2] call KOTH_fnc_async; ```
will return an UID array ?

plus i'm testing if it's possible to auto join steam friends to same squad / group

**Comment by chris579** [comment]
Grap the testing exe and test out how it would react to it. 
Of course it's possible to make a auto join but that needs a sqf workaround and a lot of error checking

**Comment by chris579** [comment]
Also this SQL-Custom entry wouldn't ban anyone.

**Comment by Torndeco** [comment]
chris579 is completely wrong there...

That SQL_CUSTOM will result in players getting RCon Banned if they have a VAC Ban.

Provided the following
extDB2 has started RCON (you dont need RCON Protocol)  
9:START_RCON:RCON

Don't forget to check VAC Settings in extdb-conf.ini.

----------

Lastly steam webapi servers are funky at times, sometimes will not respond at all, if this happens extDB2 will just kill the http request and will return 0 bans or 0 friends.

----------

Anything is possible with getFriends, just remember Steam WebAPI servers can be funky, timeout on waiting for a response 10 seconds.
Its up to you to code the SQF Logic for making use of the friends list.

**Comment by nerdalertdk** [comment]
Sorry for being a n00b, but this should work

when a player join I always check if he is the DB, if not I insert him insert. and I select if UID is in the DB.

Now this sql_custom should do both, 1: check if player exists and ban if he is VAC banned.

```sql
[existPlayerData]
;;

SQL1_1 = SELECT CASE
SQL1_2 = WHEN EXISTS(SELECT * FROM playerv2 WHERE uid = ?)
SQL1_3 = THEN 'true' ELSE 'false'
SQL1_4 = END

SQL1_INPUTS = 1-Vac_SteamID
Number of Inputs = 1
```

**Comment by nerdalertdk** [comment]
For my getfriend this is what I got, and its not working

```cpp
/*
	File: fn_vacBans.sqf
	Author: Itsatrap
	Description:
		NONE
	Parameters:
		NONE
*/
private ["_player","_playerUID","_playername","_return"];
_player 	= [_this, 0, objNull, [objNull]] call BIS_fnc_param;
_playerUID 	= getPlayerUID _player;
_playername	= name _player;
_return = true;


//***********************************

/*_resultB = call compile ("extDB2" callExtension format["2:steam:STEAMBanned:%1",_playerUID]);
if (_resultB select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error STEAMBanned: %1", _resultB]; false};

_data = call compile ("extDB2" callExtension format["5:%1", _resultB select 1]);
diag_log format["CSG: STEAMBanned data %1",_data];*/

//***********************************
_key = "extDB2" callExtension format["2:steam:GetFriends:%1",_playerUID];
_key = call compile format["%1",_key];
_key = _key select 1;
diag_log format["CSG: key data  %1",_key];

uisleep (random .03);

_queryResult = "";
_loop = true;
while{_loop} do
{
	_queryResult = "extDB2" callExtension format["4:%1", _key];
	if (_queryResult isEqualTo "[5]") then {
		// extDB2 returned that result is Multi-Part Message
		_queryResult = "";
		while{true} do {
			_pipe = "extDB2" callExtension format["5:%1", _key];
			if(_pipe isEqualTo "") exitWith {_loop = false};
			_queryResult = _queryResult + _pipe;
		};
	}else{
		if (_queryResult isEqualTo "[3]") then
		{
			diag_log format ["extDB2: uisleep [4]: %1", diag_tickTime];
			uisleep 0.1;
		} else {
			_loop = false;
		};
	};
};
_queryResult = call compile _queryResult;
if ((_queryResult select 0) isEqualTo 0) exitWith {diag_log format ["extDB2: Protocol Error: %1", _queryResult]; []};
_return1 = (_queryResult select 1);

diag_log format["CSG: GetFriends data  %1",_return1];


//***********************************
/*
if(_result) then 
{
	diag_log format["CSG: %1(%2) is vac banned",_playername,_playerUID];
	_return = false;
}
else
{
	diag_log format["CSG: %1(%2) is clean",_playername,_playerUID];
};
*/

_return
```

**Comment by Torndeco** [comment]
You forgot todo
9:START_RCON

Also its slighty bugged atm, will look @ fixing it for the next version of extDB2

**Comment by nerdalertdk** [comment]
Nice to here, all i'm trying to get is an array of UID's :)

**Comment by nerdalertdk** [comment]
Okay i can simply not get that steam friend uid list :( have tried using the async but still no luck :(

**Comment by Torndeco** [comment]
I did say it was still bugged until next version...
Should be working now with Version 54, if it is not, make a seperate issue thanks
