### ISSUE TITLE
9:STATUS_RCON

### ISSUE THREAD

**Issue by nerdalertdk** [Torndeco/extDB2#48]
Return this in log

LOG
```
[20:14:16 +02:00] [Thread 2219878764] extDB2: Extension Input from Server: 9:STATUS_RCON
[20:14:16 +02:00] [Thread 2219878764] extDB2: Invalid Format: 9:STATUS_RCON

```
RPT
```
2015/04/30, 20:14:16 "extDB2: STATUS_RCON: [0,"Error Invalid Format"]"

```

SQF code
```cpp
// RCON
	//
	_result = call compile ("extDB2" callExtension "9:START_RCON:RCON");
	if (_result select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error START_RCON:RCON: %1", _result]; false};
	
	_result = call compile ("extDB2" callExtension "9:ADD_PROTOCOL:RCON:rcon");
	if (_result select 0 isEqualTo 0) exitWith {diag_log format ["extDB2: Error ADD_PROTOCOL:RCON: %1", _result]; false};
	
	_result = call compile ("extDB2" callExtension "9:STATUS_RCON");
	diag_log format ["extDB2: STATUS_RCON: %1", _result];
	diag_log "extDB2: Connected to RCON";
```

**Comment by chris579** [comment]
I can't find the command STATUS_RCON in the documentation, I think he doesn't exists

**Comment by nerdalertdk** [comment]
at the bottom

https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol-RCON

**Comment by nerdalertdk** [comment]
I am logged in, from log file

[20:14:16 +02:00] [Thread 2282864492] Rcon: Sent Login Info
[20:14:16 +02:00] [Thread 2282864492] Rcon: Logged In

**Comment by Torndeco** [comment]
Its actually 9:RCON_STATUS
Also using it straight after connecting rcon without a sleep risks it reporting false before it gets a chance to connect to server

**Comment by nerdalertdk** [comment]
Well right now I'm only testing her out ;)

Got MySQL custom working fine. 
Next is steam and redis :)
