### ISSUE TITLE
SQL_Custom

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#49]
I get no return ([1,[]]) for:

####################
[getPlayerAdacInfo]
SQL1_1 = SELECT playerid, name, cash, bankacc, adminlevel, adaclevel, adac_gear, adac_inv, blacklist
SQL1_2 = FROM players WHERE playerid=?;
SQL2_1 = UPDATE players SET lastJoin=Now() WHERE playerid=?;

SQL1_INPUTS = 1
SQL2_INPUTS = 1
Number of Inputs = 1
OUTPUT = 1-STRING, 2-STRING, 3, 4, 5, 6, 7, 8, 9
#####################

And why is ?-AltisLifeRPGArray not longer supported?

**Comment by Torndeco** [comment]
1) It only returns output from last statement. The last statement is an update sql statement, it doesn't return anything

2) Read the wiki

**Comment by shukari** [comment]
also no return for:

##############################
[getPlayerCivInfo]
SQL1_1 = UPDATE players SET lastJoin=Now() WHERE playerid=?;
SQL2_1 = SELECT playerid, cash, bankacc, adminlevel, civ_licenses, civ_gear, arrested, leben, life_hunger, life_thirst, life_battery
SQL2_2 = FROM players JOIN zusatz_player ON playerid=pid WHERE playerid=?;

SQL1_INPUTS = 1
SQL2_INPUTS = 1
Number of Inputs = 1
OUTPUT = 1-STRING, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
##############################

**Comment by shukari** [comment]
my fault.... wrong uid...

**Comment by nerdalertdk** [comment]
You change you Db layout so it automatic update LastJoin
that way you can remove 

```sql
ALTER TABLE `DBNAME `.`player` 
CHANGE COLUMN `lastJoin` `lastJoin` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ;
```

```
##############################
[getPlayerCivInfo]
SQL1 = SELECT playerid, cash, bankacc, adminlevel, civ_licenses, civ_gear, arrested, leben, life_hunger, life_thirst, life_battery
SQL2 = FROM players JOIN zusatz_player ON playerid=pid WHERE playerid=?;

SQL1_INPUTS = 1
Number of Inputs = 1
OUTPUT = 1-STRING, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11
##############################
```
not tested

**Comment by shukari** [comment]
fuck thanks man...

**Comment by shukari** [comment]
For:
ALTER TABLE `players` CHANGE `lastJoin` `lastJoin` DATETIME on update CURRENT_TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP;

Get:
#1067 - Invalid default value for 'lastJoin'

**Comment by nerdalertdk** [comment]
might be your Mysql Version works fine for me on mysql 5.6

**Comment by nerdalertdk** [comment]
Bonus info :)
It looks like as of mysql 5.6.5, you can use CURRENT_TIMESTAMP with DATETIME fields. See
