### ISSUE TITLE
extDB - A3Wasteland

### ISSUE THREAD

**Issue by LouDnl** [Torndeco/extDB2#50]
Hi Torndeco,

Not really an issue yet, but I would like your opinion on something.
Can you look at these two topics please?
http://forums.a3wasteland.com/index.php?topic=1532.0
http://forums.a3wasteland.com/index.php?topic=1476.0

Thanks in advance!

**Comment by Torndeco** [comment]
SImple version its more than likely an issue with SQF Code.
While i may have help initially with added it to A3Wasteland, Rev went and redone all the code so its more compatible with ini saving format.
So its up to you guys to debug the issue.

Setup up a test server + use the debug version of extDB2.
Once you got missing objects from database check the log entries if they are getting removed from server or if they never got saved initially.

That way you will have the area of code narrowed down, then add some debug statements
Either using diag_log or extDB2 logging protocol or killzonekid log extension.

-----------------------

Personally the persistence code in A3Wasteland should be redone long time, i said so as much back when i added extDB.
Just use triggers for object deletion + just don't bother with saving damage (its nice to have but not worth the fps lose on a wasteland server.

**Comment by LouDnl** [comment]
Thanks for your reply Torndeco.
