### ISSUE TITLE
Adjust Return Value for RCON Commands

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#51]
Hey Torndeco,

the RCON Comamnds are working fine but for a couple of commands there is just returned the value if it's done(e.g. #userlist). Is it possible to retrieve the returned array?
The command
```java
2:rcon:#userlist
```

would just return "[1]" instead of a whole list of users.

**Comment by Torndeco** [comment]
#userlist is an ingame command
players is the rcon command

Currently RCON Protocol doesn't return anything yet, its a WIP.
Got mission list done, currently working on return values for players

**Comment by chris579** [comment]
Nice man!

**Comment by Torndeco** [comment]
Now working in Version 54 + Rcon code is improved aswell.
Commands are send to server straight away etc..

players + missions return info

**Comment by chris579** [comment]
You're a god, big thanks appreciate it!
