### ISSUE TITLE
extDB2 and ASM

### ISSUE THREAD

**Issue by manzarek123** [Torndeco/extDB2#53]
Hello,
This is a strange bug that maybe you are aware of.
if i use
"-mod=@life_server;@asm;@extDB2"
There is no problem server works fine.

But if i use
"-mod=@life_server;@extDB2;@asm"

Impossible to connect, extDB2 will not load, nothing will load.

Probably that the order the engine will load them is important here.

Thank you for everything

tested with extDB2 v49

**Comment by Torndeco** [comment]
Arma engine handles -mod  + loading Database
Post issue @ http://feedback.arma3.com/my_view_page.php
