### ISSUE TITLE
Add a wiki entry for the HTTP connection

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#54]
It would be nice to have a documentation of the HTTP connection because I have no real clue what it is or what it is able to do.

**Comment by Torndeco** [comment]
Example (there is no ADD_DATABASE:HTTP)
9:ADD_DATABASE_PROTOCOL:HTTP:HTTP_RAW:HTTP:FULL_RETURN

1:HTTP:POST:fooooooooooooooooooo
2:HTTP:POST:foooooooooooooooooo
2:HTTP:GET:foooooooooooooooooo

All it is HTTP  Post + Get requests

For it to be of any use you need to make up a webserver that handles the HTTP Requests + sends info back to armaserver.

**Comment by chris579** [comment]
AH, I understand, what about a quick info in the wiki? Would you add this and expand the whole thing a bit?

**Comment by Torndeco** [comment]
I will when i get time, wiki needs time to do some nice formatting...
But there really is nothing else to the Protocol, all the work is done by the webserver

**Comment by nerdalertdk** [comment]
Have not played with the get irk yet but would I be able to get a Json array and use sqf to handle the array?
Planing to use this for an in game leader board / top 10 players

**Comment by chris579** [comment]
Why would you use the http function for that? A simple mysql query is more easier and faster...

**Comment by nerdalertdk** [comment]
Because we can :) plus just testing what's posible

**Comment by Torndeco** [comment]
Updated wiki
