### ISSUE TITLE
Autoban for BattlEye Filter Restrictions

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#59]
Adding a configurable autoban for RCON protocol which bans players automatically on BE kick. Maybe a config for different ban times and ban messages for different BE filters.

**Comment by Torndeco** [comment]
Already making another tool that will cover this scenario and more....
But have no plans atm to make this tool public or not

http://forums.bistudio.com/showthread.php?179727-extDB-%28arma3-extension-linux-windows%29&p=2939478&viewfull=1#post2939478

**Comment by chris579** [comment]
Would be nice if you release this when it's ready, would appreciate it!
