### ISSUE TITLE
Wiki Updates

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extDB2#60]
Need to go through wiki entries + make sure they are all up to date.

**Comment by nerdalertdk** [comment]
would be nice if you add how i would ban a player thru RCON:COMMAND, there is no way to get the GUID thru arma commands

**Comment by Torndeco** [comment]
You can ban players via GUID
https://community.bistudio.com/wiki/BattlEye#GUID_banning

Please make a seperate issue next time....
Since i will delete these messages later today to keep it clean

**Comment by kkotowick** [comment]
On this topic, would it be possible to add some more details about how the OUTPUT command/syntax works in the prepared statements (SQL_CUSTOM_V2)?

**Comment by Torndeco** [comment]
https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol--SQL_CUSTOM_V2
