### ISSUE TITLE
extDB config not loaded properly when saved as UTF-8

### ISSUE THREAD

**Issue by chris579** [Torndeco/extDB2#65]
I saved my extDB config with UTF-8 encoding due to special characters for bad player name kicking.

My regex:
```
;;Bad Playername Regex_1 = [^A-Za-z0-9Ωω\.-_\[\]\(\)\/\%\=\?\°\^\+ \~\*\|üäöÜÄÖß]
```

My log:
```
extDB2: Version: 59
extDB2: https://github.com/Torndeco/extDB2
extDB2: Windows Debug Version

Message: All development for extDB2 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB2 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 20/02/15


extDB2: Found extdb-conf.ini
extDB2: Incompatiable Config Version: 0,  Required Version: 5
```

**Comment by Torndeco** [comment]
Try save as UTF-8 without BOM and check its your regex rules are working correctly.
GIve me a shout if it works for you or not  
Thanks

**Comment by chris579** [comment]
I saved it without BOM already and checked the regex rules already with a regex checker, the rule works fine but the config is still not loaded.

**Comment by Torndeco** [comment]
Works fine, you can send your config file in skype one of the days if you like.
You just need to save the file without BOM

**Comment by chris579** [comment]
Whats your Skype name?
