### ISSUE TITLE
a3wasteland.ini

### ISSUE THREAD

**Issue by Soloknight** [Torndeco/extDB2#66]
I working on added some new stuff in Mysql and got it working but not 100% accurate was wondering it we could talk about some of the calls I'm doing and the result that is it's getting. I rather if possible do it on Teamspeak or alternative. no big deal if you can't, I'm new to this mysql stuff and figuring it out ect. ts.g4-gamers.com

**Comment by Torndeco** [comment]
If you like you can donate to extDB2 development, or you could just pay me for some help with your mission / sql.
Since looking over someone elses code + sql scheme / statements can be time consuming

Otherwise i recommend you check out a3wasteland forums

**Comment by Soloknight** [comment]
I can make a donation ;-)

**Comment by Torndeco** [comment]
Normally on Skype
nickname = torndeco

Send me a message what you want to me to look at it and can take it from there.
Busy atm, so might not get time to respond / look at it till tomorrow
