### ISSUE TITLE
? char is not being interpreted

### ISSUE THREAD

**Issue by HatchetHarry** [Torndeco/extDB2#68]
I didnt send it via skype, because it could interest others too: 

This simple query drives me nuts: 

This one is working: 
;;["insertCustomWithDup2:server_hive:HiveDescription:(""122331d""):HiveDescription=123",1,false]execvm "functions\general_server\database\fn_s_asyncDBCall.sqf"
[insertCustomWithDup]
SQL1_1 = INSERT INTO $CUSTOM_1$ ($CUSTOM_2$) 
SQL1_2 = VALUES $CUSTOM_3$
SQL1_3 = ON DUPLICATE KEY UPDATE $CUSTOM_4$

Number of Custom Inputs = 4

This one is working: 
;;["insertCustomWithDup2:server_hive:HiveDescription:(""122331d""):HiveDescription=123",1,false]execvm "functions\general_server\database\fn_s_asyncDBCall.sqf"
[insertCustomWithDup2]
SQL1_1 = INSERT INTO ? ($CUSTOM_1$) 
SQL1_2 = VALUES $CUSTOM_2$
SQL1_3 = ON DUPLICATE KEY UPDATE $CUSTOM_3$
SQL1_INPUTS = 1

Number of Inputs = 1
Number of Custom Inputs = 3

The first placeholder is not interpreted correctly: 
Column 1  : [18:49:22 +02:00] [Thread 11764] extDB2: SQL_CUSTOM_V2: Error StatementException: MySQL: [MySQL]: [Comment]: mysql_stmt_prepare error	[mysql_stmt_error]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '? (HiveDescription) VALUES ("122331d") ON DUPLICATE KEY UPDATE HiveDescription=1' at line 1	[mysql_stmt_errno]: 1064	[mysql_stmt_sqlstate]: 42000	[statemnt]: 

INSERT INTO ? (HiveDescription) VALUES ("122331d") ON DUPLICATE KEY UPDATE HiveDescription=123

I double checked it a dozen of times, but i dont find the problem. Why is he not taking the first argument. What do i forget the whole time?
The server hive table is just my victim, please do not ask for the sql query reason.
It is not blocking me completely, but i would like to use non custom queries as much as i can, because they just have to be forwarded. The Insert statement has been constructed lazy queries. 

Thank you for having a look on it and your great work :-)

**Comment by Torndeco** [comment]
You can't use ? for a TABLE NAME.
http://en.wikipedia.org/wiki/Prepared_statement
