### ISSUE TITLE
Arma dev 1.46

### ISSUE THREAD

**Issue by nerdalertdk** [Torndeco/extDB2#69]
Since Arma 2: Operation Arrowhead it is possible to expand the game's functionality via custom DLL extensions. These offer powerful features to the creative mod(e) out there, but can also open the game to attack. The enhanced BattlEye protection in 1.46 will require extensions to be white-listed, or their access to the game's processes will be blocked. In order to get your extension white-listed, please contact BattlEye support via its web form or support[at]battleye.com. Be sure to include the file name, a description and possibly a download link. You may also contact Online Services Consultant David Foltýn via his Twitter or the forums to speed things along. We are discussing ways of dealing with fast-moving extension development within communities, as well as a more robust extension framework generally.

http://dev.arma3.com/post/sitrep-00109

are you aware of this ?

**Comment by Torndeco** [comment]
Yes i am aware of this.
