### ISSUE TITLE
Question: Prepaired Statements

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#72]
A short question... need i do ' around ? for char types... or do this extDB2 itself...

UPDATE player SET example=? WHERE active=?;
or
UPDATE player SET example='?' WHERE active='?';

Thank you for your answer ;D

**Comment by Torndeco** [comment]
Don't wrap ? in quotations, otherwise you would be telling SQL its a string containing the character ?

https://github.com/Torndeco/extDB2/blob/master/examples/sql_custom_v2/example.ini
https://github.com/A3Wasteland/ArmA3_Wasteland.Altis/blob/extDB2_beta/sql_custom/a3wasteland.ini
