### ISSUE TITLE
Get no result...

### ISSUE THREAD

**Issue by shukari** [Torndeco/extDB2#73]
Here thats the example from the ini....

[checkAllreadyInGang]
SQL1_1 = SELECT COUNT(*) FROM gangs WHERE active='1' AND members LIKE ?;
SQL1_INPUTS = 1
Number of Inputs = 1
OUTPUT = 1

input -> ["checkAllreadyInGang:%765X1198X93X101%",2]

output (log) -> "3:06:42 "[error pos] asyncCall - isNil-check2 (["checkAllreadyInGang:%765X1198XX93XX101%",2])"

output -> nil

What do i wrong?!?

**Comment by shukari** [comment]
also -> [03:05:09:609 +02:00] [Thread 9796] extDB2: SQL_CUSTOM_V2: Version 9 Detected, Latest Version 12 Available

What must i do to update... only change the number in the ini?!?

**Comment by shukari** [comment]
also -> link in "https://github.com/Torndeco/extDB2/blob/master/Changelog%20SQL_CUSTOM.txt" is broken -> https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol--SQL_CUSTOM must be now -> https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol--SQL_CUSTOM_V2

;D

**Comment by Torndeco** [comment]
Use the debug version of extDB2 and send me the extDB2 log
Not interested in any rpt logging a mission or mod is doing

**Comment by shukari** [comment]
"Not interested in any rpt logging a mission or mod is doing"

not so harsh pls... i want only help you... and me ;D ... you have the log in 2 minutes...

**Comment by shukari** [comment]
mega shame on me... i make a mistake... that debugging is n1... everything is ok ;D

But how can i "update" the SQL_Custom Protokoll...?!?

**Comment by Torndeco** [comment]
https://github.com/Torndeco/extDB2/blob/master/Changelog.txt#L49-L53
Thats the only difference
