### ISSUE TITLE
Don't know if its on my side (99% sure it is), better ask the boss

### ISSUE THREAD

**Issue by Ppgtjmad** [Torndeco/extDB2#76]
Hello,

Everything is right there -> https://github.com/Ppgtjmad/TEST
extDB - 63

I tried to update AltisLife to the latest extDB version, seems that I can't get a proper query result. And yeah am still using raw sql because am lazy (will do later).

Thanks.

**Comment by Torndeco** [comment]
No issue with extDB2, its purely sqf code.

You got all the debug info to figure it out via extDB2 Debug Logs + RPT Logs + async sqf code.
