### ISSUE TITLE
Strip Behavior

### ISSUE THREAD

**Issue by ithr0n** [Torndeco/extDB2#77]
Hey.. 

I think it is not really an issue, but I have a problem with a query...

```
[wantedFetchID]
;;

SQL1_1 = SELECT wantedID, wantedName FROM wanted WHERE active='1' AND wantedID in (?);
SQL1_INPUTS = 1-NoStrip

Number of Inputs = 1
OUTPUT = 1-String, 2-String
```

My SQF code is here:

```
_inStatement = "";
{
	if(_inStatement == "") then
	{
		_inStatement = _x;
	}
	else
	{
		_inStatement = _inStatement + "','" + _x;
	};
} forEach _units;

if (_inStatement != "") then {
	_inStatement = "'" + _inStatement + "'";
	_result = format["wantedFetchID:%1",_inStatement];
	waitUntil{!DB_Async_Active};
	_queryResult = [_result,2,true] call DB_fnc_asyncCall;
} else {
	_queryResult = [];
};
```

The query executed on the server is this:
SELECT wantedID, wantedName FROM wanted WHERE active=''1'' AND wantedID in (''\''76561197972302561\'',\''76561198063100739\'''')

As you can see, the quotes are escaped again.. I tried to change the Input behavior to None, Strip, String, ...
But it is not working for me....

Thanks for help! :-)

**Comment by Torndeco** [comment]
String, Strip, String_Escape_Quotes  are all different Options
https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol--SQL_CUSTOM_V2

Also you need to use CUSTOM_INPUT for "in (?)"
