### ISSUE TITLE
v64 Crashes

### ISSUE THREAD

**Issue by Torndeco** [Torndeco/extDB2#80]
Downgrade to v63
There is an issue with the JEMalloc that if triggered can cause a server crash

**Comment by chris579** [comment]
RPT: > extDB2.dll!731fec2a() Unknown
  [Frames below may be incorrect and/or missing, no symbols loaded for extDB2.dll]

**Comment by Torndeco** [comment]
Unless its a full RPT log entry + extDB2 Debug logs, i not really interested...
Just assume + paste snippets of RPT you leave out important info etc...

Anyway its already a known issue
