### ISSUE TITLE
Longtext causes immediate crash

### ISSUE THREAD

**Issue by kkotowick** [Torndeco/extDB2#81]
If a database table has a "longtext" column, then extDB2 will crash every time it tries to read from that table. I have tested on v62, v63, and v64. This issue does not occur with a "text" or "mediumtext" column.

**Comment by Torndeco** [comment]
Type | Maximum length
-----------+-------------------------------------
  TINYTEXT |           255 (2 8−1) bytes
      TEXT |        65,535 (216−1) bytes = 64 KiB
MEDIUMTEXT |    16,777,215 (224−1) bytes = 16 MiB
  LONGTEXT | 4,294,967,295 (232−1) bytes =  4 GiB


Text = long enough for arma

Its a known issue
To fix it would require dropping Poco LIbrary and rewriting the database code.
Its alot of work, but the advantages would be proper procedure support / better memory usage etc, slightly faster (but prob not by any measurable amount.

Its alot of work for very little benefits, so unless someone wants code it or to pay me todo it.
Its prob won't get fix anytime soon
