### ISSUE TITLE
Multi-Statements

### ISSUE THREAD

**Issue by Aeneas1** [Torndeco/extDB2#83]
Hello, is it possible to make some changes, which allow to send more than one SQL statement at the time. Of course only for Codes without a result (call_type = 1). 
I need this to save dynamic Array in the DB.

 ex. ["Update table1 set x = y; Update table2 set t = p;",1] call DB_fnc_asyncCall;

**Comment by Torndeco** [comment]
DB_fnc_asyncCall  is SQF Code
The SQF code in github is just an example how to talk to extDB2

But regardless,
extDB2 will only execute 1 SQL Statement at a time.
This behaviour won't be changing, as it would make it easier for arma hackers to inject SQL Commands (if you are using SQL_RAW).

--------------

If you want to execute multiple statements via a single callExtension
Look @ using SQL_CUSTOM_V2

No-one really should be using SQL_RAW its insecure + slower.
