### ISSUE TITLE
Feature Request: Error Details

### ISSUE THREAD

**Issue by kkotowick** [Torndeco/extDB2#86]
I'm having a nightmare of a time trying to debug an issue here, so I figured I'd request this tool. When I make a request by calling the extension from my SQF script, it returns the error "Error Statement Exception". Normally I would just open up the extDB2-test.exe program and enter the same statement so I can see exactly what the error is. However, running the same statement in the test program doesn't return an error. So, now I have no way of determining what the error actually is, since I can't get those details when calling the extension from SQF code.

Because of this, I would like to request that the error message that is returned to an ARMA script be the same as the error message that is displayed in the extDB2-test.exe program, to make debugging much simpler.

**Comment by Torndeco** [comment]
Look @ the log files for more detailed error info, exact same error output as the test program

There is also Debug Info that logs alot more info aswell

**Comment by kkotowick** [comment]
Ok, that works too :). In that case, let me turn this into a bug report / help ticket. I'm calling two prepared statements in a row, and the second one is returning the error "commands out of sync". Researching this for MySQL shows that this is usually due to not using "mysql_free_result" or associated functions in the right order, often an issue with stored procedures. As it happens, the first prepared statement I'm calling runs a stored procedure on the database. The two prepared statements look like this:

[createCharacter]
SQL1_1 = CALL db.createCharacter(?,?,?) // returns nothing
Number of Inputs = 3
SQL1_INPUTS = 1,2,3

[getCharacters]
SQL1_1 = SELECT ap.characterID, ap.name FROM db.players AS ap WHERE ap.playerid = ?
Number of Inputs = 1
SQL1_INPUTS = 1
OUTPUT = 1

And my extDB2 calls look like this:

2:sql:createCharacter:"7567561212755567":"New Character Name":CIV
2:sql:getCharacters:"7567561212755567"

And that second command will return the error:

[13:38:55:892298 --7:00] [Thread 11188] extDB2: SQL_CUSTOM_V2: Error StatementException: MySQL: [MySQL]: [Comment]: mysql_stmt_prepare error    [mysql_stmt_error]: Commands out of sync; you can't run this command now        [mysql_stmt_errno]: 2014        [mysql_stmt_sqlstate]: HY000    [statemnt]: SELECT ap.characterID, ap.name FROM db.players AS ap WHERE ap.playerid = ?

**Comment by Torndeco** [comment]
If you want to me look into this i will need the ability to reproduce it locally

So i would need the 
Database Tables
The  stored procedure  you are calling etc
Full extDB log files doesn't hurt either

**Comment by kkotowick** [comment]
Nevermind, you can can close this. The issue was in the stored procedure.
