### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by harmdhast** [Torndeco/extDB2#87]
Hello,
Do you plan to support postgresql ?
Is this possible ? 
I know C++ a little bit and I don't know if it's like possible and/or easy to make a postgresql port.

Thanks

**Comment by Torndeco** [comment]
If you know CMake Build System just help out at
https://github.com/pocoproject/poco/issues/900

**Comment by harmdhast** [comment]
Thanks, I don't know that at all. I will grab more information on wikis and stuff. So basicly, it's not possible to have Postgres support because of poco does not actually supporting it ?

**Comment by harmdhast** [comment]
I don't think I can handle the Postgre support. So if you can guide me through the process steps or something. I did a little bit of C++ but I never used any external libraries or Cmake. I was just wondering around with code blocks and thats all ^^.
If you have any links for me to understand and modify your work, please give them to me.

Thanks a lot, your work is amazing.

**Comment by moreni57** [comment]
where is extDB at this link https://github.com/Torndeco/extdb

**Comment by moreni57** [comment]
beacause i need version extdb.so and ini file. thank

**Comment by Torndeco** [comment]
@mreni57
extDB repo is no longer available.
Its got retired around 8 months ago + can cause armaserver to crash

@harmdhast 
Yeah thats why i pointed you @ the issue. 
The main thing holding it up is the CMake system needs to be updated.

I really don't have the time to walk somethrough setting up a build system

CMake build system is used for MySQL, Poco Libraries, & extDB2

Windows = VS2013 (haven't tried vs2015 yet)
Libraries are
https://github.com/Torndeco/poco
MySQL you will need to compile from source code for vs2013
Boost you can grab precompiled for vs2013
Intel TBB you can grab precompiled for vs2013

Linux builds i use a schroot 32bit enviroment.
Same libraries as above
Just custom compile Boost + MySQL + Poco  Libraries

**Comment by harmdhast** [comment]
Thanks a lot.
I will look at this. 
The question is can I modify your poco source to include the beta Postgres branch and then get it working on extDB2 ? Or do you plan to include Postgres support later ? 
I am already working on how to code with VS and learning Boost and Poco libs.

Thanks again and sorry for taking your time :)
