### ISSUE TITLE
extDB2 Linux version has non executable file

### ISSUE THREAD

**Issue by DistortedDorian** [Torndeco/extDB2#88]
The extDB2 update 66 does not include any executable files (.so / .lbb) which the old extDB did, it only have a configuration file: extdb-conf.ini.
How can the mod be used if no executable files tells the server what to do?
![in0y28o](https://cloud.githubusercontent.com/assets/4209824/9290079/49de34d0-4385-11e5-80f1-f8ff09120912.png)

**Comment by Torndeco** [comment]
Just use v65...
I haven't had time yet to compile the linux versions yet

**Comment by DistortedDorian** [comment]
Seems correct, thanks.
