### ISSUE TITLE
wrong bind parameters count

### ISSUE THREAD

**Issue by Nokman** [Torndeco/extDB2#89]
[playernameadd]
;;
SQL1_1 = update players as p, players as old set p.aliases=concat(p.aliases,',',old.name),p.playerid=old.playerid and p.playerid='?' and (old.aliases != '?' and old.aliases != '%,?,%' and old.aliases not like '%,?' and old.aliases not like '?,%');
SQL1_INPUTS = 1 2 2 2 2
Number of Inputs = 2

[Thread 3003872054] extDB2: Extension Input from Server: 1:798390:playernameadd:76561197960667748:Nokman
[Thread 2593527627] extDB2: SQL_CUSTOM: Trace: UniqueID: 0 Input: playernameadd:76561197960667748:Nokman
[Thread 2593527627] extDB2: SQL_CUSTOM: Error StatementException: MySQL: [MySQL]: [Comment]: wrong bind parameters count	[statemnt]: update players as p, players as old set p.aliases=concat(p.aliases,',',old.name),p.playerid=old.playerid and p.playerid='?' and (old.aliases != '?' and old.aliases != '%,?,%' and old.aliases not like '%,?' and old.aliases not like '?,%');

I was doing a mistake or it returns the false statement. In the Console to do it.

**Comment by Torndeco** [comment]
Wrong binds is an MySQL error, means you have incorrect number of inputs.
i.e you are putting ? inside quotations.
MySQL is a string containing ?

**Comment by chris579** [comment]
SQL_INPUTS uses comma as seperator:
SQL_INPUTS = 1,2,2,2,2
