### ISSUE TITLE
Compile With (GNU libc) 2.12

### ISSUE THREAD

**Issue by MattDogIRC** [Torndeco/extDB2#92]
i need your help please trying to get this to work with an exile server but can't because i'm on centos 6 and it has ldd (GNU libc) 2.12

Is it possible to recompile the source myself on 2.12 or is there an earlier release which can be ran on 2.12?

**Comment by Torndeco** [comment]
No idea, it could be possible

-----------------------
Easiest method
Setup a chroot enviroment,
Compile custom version of Poco from my github using cmake
Then compile extDB2

The problems are your GCC version will prob be older version.
You may run into issues compiling the code, if some of c++ 11 features are in your gcc version.

-----------------------

Eitherway its not supported, so i don't recommend it unless you know what you are doing.
Easier to just upgrade your Linux Distro
