### ISSUE TITLE
extDB2: Error Invalid Format: 9:SHUTDOWN

### ISSUE THREAD

**Issue by MattDogIRC** [Torndeco/extDB2#95]
[01:22:51 --4:00] [Thread 29869] extDB2: Database Type: MySQL
[01:22:51 --4:00] [Thread 29869] extDB2: Database Session Pool Started
[01:22:51 --4:00] [Thread 29869] extDB2: SQL_CUSTOM_V2: Loading Template Filename: /home/tcagame/boba/4/@ExileServer/extDB/sql_custom_v2/exile.ini
[01:22:51 --4:00] [Thread 29869] extDB2: SQL_CUSTOM_V2: Version 8 Detected, Latest Version 12 Available
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:ADD_DATABASE_PROTOCOL:exile:SQL_CUSTOM_V2:943370:exile
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:SHUTDOWN
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:SHUTDOWN

any help grately appreciated
when i join the server pickup some stuff and reconnect server craches

**Comment by Torndeco** [comment]
Need full log file not a snippet  thanks

**Comment by MattDogIRC** [comment]
extDB2: Version: 65
extDB2: https://github.com/Torndeco/extDB2
extDB2: Linux Version
Message: All development for extDB2 is done on a Linux Dedicated Server
Message: If you would like to Donate to extDB2 Development
Message: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2SUEFTGABTAM2
Message: Also leave a message if there is any particular feature you would like to see added.
Message: Thanks for all the people that have donated.
Message: Torndeco: 20/02/15


extDB2: Found extdb-conf.ini
extDB2: Detected 16 Cores, Setting up 6 Worker Threads


[01:22:51 --4:00] [Thread 29869] extDB2: Database Type: MySQL
[01:22:51 --4:00] [Thread 29869] extDB2: Database Session Pool Started
[01:22:51 --4:00] [Thread 29869] extDB2: SQL_CUSTOM_V2: Loading Template Filename: /home/tcagame/boba/4/@ExileServer/extDB/sql_custom_v2/exile.ini
[01:22:51 --4:00] [Thread 29869] extDB2: SQL_CUSTOM_V2: Version 8 Detected, Latest Version 12 Available
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:ADD_DATABASE_PROTOCOL:exile:SQL_CUSTOM_V2:943370:exile
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:SHUTDOWN
[01:27:30 --4:00] [Thread 29869] extDB2: Error Invalid Format: 9:SHUTDOWN

**Comment by MattDogIRC** [comment]
13:41:21 "ExileServer - Installed extDB2 version: 65"
13:41:21 "ExileServer - Connected to database!"
13:41:21 "ExileServer - Database protocol initialized!"
13:41:21 "Player/BIS_fnc_log: [preInit] ExileServer_fnc_preInit (106.995 ms)"
13:41:21 Error: Bone world root doesn't exist in skeleton OFP2_ManSkeleton
13:41:21 Error: Bone hips doesn't exist in skeleton OFP2_ManSkeleton
13:41:30 Mission read.
13:41:30 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
13:41:30 "Player/BIS_fnc_log: [script] initServer.sqf"
13:41:30 "Player/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0.976562 ms)"
13:41:30 "Player/BIS_fnc_log: [postInit] BIS_fnc_initParams (0 ms)"
13:41:30 "Player/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0 ms)"
13:41:30 "Player/BIS_fnc_log: [postInit] BIS_fnc_sharedObjectives (0 ms)"
13:41:30 "Player/BIS_fnc_log: [postInit] BIS_fnc_3dMarkers (0 ms)"
13:41:30 "Player/BIS_fnc_log: [postInit] ExileClient_fnc_postInit (0 ms)"
13:41:30 "ExileServer - Job with handle 10000 added."
13:41:30 "ExileServer - Job with handle 10001 added."
13:41:30 "ExileServer - Job with handle 10002 added."
13:41:30 "ExileServer - Job with handle 10003 added."
13:41:30 "ExileServer - Job with handle 10004 added."
13:41:30 "ExileServer - Job with handle 10005 added."
13:41:30 Weather was forced to change
13:41:30 "ExileServer - Job with handle 10006 added."
13:41:30 "ExileServer - Initializing game world..."
13:41:30 "ExileServer - Loading territories from database..."
13:41:30 "ExileServer - Done loading territories!"
13:41:30 "ExileServer - Loading constructions from database..."
13:41:30 "ExileServer - Done loading constructions!"
13:41:30 "ExileServer - Loading vehicles from database..."
13:41:30 "ExileServer - Done loading vehicles!"
13:41:30 "ExileServer - Loading containers from database..."
13:41:30 "ExileServer - Done loading containers!"
13:41:30 "ExileServer - Creating spawn zone vehicles..."
13:41:32 "ExileServer - Spawning Dynamic Vehicles. GridSize: 2200 Vehs/Grid : 2"
13:41:43 Strange convex component317 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
13:41:43 Strange convex component318 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
13:41:43 Strange convex component319 in a3\rocks_f\blunt\bluntrock_wallv.p3d:geometry
13:41:46 "ExileServer - Dynamic vehicles spawned. Count : 234"
13:41:46 "ExileServer - Game world initialized! Let the fun begin!"
13:41:46 "ExileServer - Running maintenance!"
13:41:46 "ExileServer - Maintenance done. 0 territories deleted."
13:41:46 "ExileServer - Server is up and running! Version: 0.9.20"
13:41:46 "Player/BIS_fnc_log: [postInit] ExileServer_fnc_postInit (15737 ms)"
13:41:46 Exile_Cosmetic_MG: MainTurret - unknown animation source mainTurret
13:41:46 Exile_Cosmetic_MG: MainGun - unknown animation source mainGun
13:41:46 Exile_Cosmetic_MG: Ammo_belt_rotation - unknown animation source ReloadAnim
13:41:46 Exile_Cosmetic_MG: Bolt_reload_begin - unknown animation source reloadMagazine
13:41:46 Exile_Cosmetic_MG: muzzleFlash - unknown animation source muzzle_source
13:41:46 Exile_Cosmetic_MG: zaslehROT - unknown animation source muzzle_source_rot
13:41:46 Exile_Cosmetic_MG: AddAutonomous_unhide - unknown animation source autonomous_unhide
13:41:46 Exile_Cosmetic_MG: bullet001_reload_hide - unknown animation source revolving
13:41:46 Exile_Cosmetic_UAV: RotorImpactHide - unknown animation source rotorHFullyDestroyed
13:41:46 Exile_Cosmetic_UAV: TailRotorImpactHide - unknown animation source tailRotorHFullyDestroyed
13:41:46 Exile_Cosmetic_UAV: propeller1_rotation - unknown animation source rotorH
13:41:46 Exile_Cosmetic_UAV: propeller2_rotation - unknown animation source rotorV
13:41:46 Exile_Cosmetic_UAV: propeller1_hide - unknown animation source rpm
13:41:46 Exile_Cosmetic_UAV: MainTurret - unknown animation source mainTurret
13:41:46 Exile_Cosmetic_UAV: MainGun - unknown animation source mainGun
13:41:46 Land_Box_AmmoOld_F: Ammo_hide - unknown animation source Ammo_source
13:41:46 Land_Box_AmmoOld_F: AmmoOrd_hide - unknown animation source AmmoOrd_source
13:41:46 Land_Box_AmmoOld_F: Grenades_hide - unknown animation source Grenades_source
13:41:46 Land_Box_AmmoOld_F: Support_hide - unknown animation source Support_source
13:41:46 "Player/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 25886 ms -----"
13:41:52 "ExileServer - Player Boba Fett (UID 76561198043182095) connected!"
13:41:52 Game started.
13:41:52 "ExileServer - Main thread started"
13:42:10 Server: Unhandled user message Type_261
13:45:11 Game finished.
13:45:11 Warning: Cleanup player - person 2:663 not found
13:45:11 Waiting for next game.
13:45:12 Mission Exile.Altis read from bank.
13:45:15 Roles assigned.
13:45:15 Reading mission ...
13:45:15 Starting mission:
13:45:15  Mission file: Exile (__cur_mp)
13:45:15  Mission world: Altis
13:45:15  Mission directory: mpmissions\__cur_mp.Altis\
Attempt to override final function - bis_functions_list
Attempt to override final function - bis_functions_listpreinit
Attempt to override final function - bis_functions_listpostinit
Attempt to override final function - bis_functions_listrecompile
13:45:16 "Player/BIS_fnc_log: [BIS_fnc_preload] ----- Initializing scripts in Exile -----"
13:45:16 "Player/BIS_fnc_log: [recompile] recompile BIS_fnc_missionTasksLocal"
Attempt to override final function - bis_fnc_missiontaskslocal
13:45:16 "Player/BIS_fnc_log: [recompile] recompile BIS_fnc_missionConversationsLocal"
Attempt to override final function - bis_fnc_missionconversationslocal
13:45:16 "Player/BIS_fnc_log: [recompile] recompile BIS_fnc_missionFlow"
Attempt to override final function - bis_fnc_missionflow
13:45:16 "Player/BIS_fnc_log: [preInit] BIS_fnc_diagKey (0 ms)"
13:45:16 "Player/BIS_fnc_log: [preInit] BIS_fnc_feedbackMain (10.0098 ms)"
13:45:16 "Player/BIS_fnc_log: [preInit] BIS_fnc_missionHandlers (0 ms)"
13:45:16 "Player/BIS_fnc_log: [preInit] BIS_fnc_getServerVariable (0 ms)"
13:45:16 "Player/BIS_fnc_log: [preInit] ExileClient_fnc_preInit (189.941 ms)"
13:45:17 "ExileServer - Server is loading..."
13:45:17 Client: Nonnetwork object e2dada00.
13:45:17 "ExileServer - Installed extDB2 version: 65"
13:45:17 "ExileServer - Connected to database!"
13:45:17 "ExileServer - MySQL connection error!"
13:45:17 "ExileServer - Please have a look at @ExileServer/extDB/logs/ to find out what went wrong."
13:45:17 "ExileServer - MySQL Error: Failed to initialize database protocol: [0,"Error Invalid Format"]"
13:45:17 "ExileServer - Server will shutdown now :("
13:45:17 "Player/BIS_fnc_log: [preInit] ExileServer_fnc_preInit (87.0361 ms)"
13:45:17 Mission read.
13:45:17 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
13:45:17 "Player/BIS_fnc_log: [script] initServer.sqf"
13:45:17 "Player/BIS_fnc_log: [postInit] BIS_fnc_missionFlow (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] BIS_fnc_initParams (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] BIS_fnc_initRespawn (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] BIS_fnc_sharedObjectives (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] BIS_fnc_3dMarkers (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] ExileClient_fnc_postInit (0 ms)"
13:45:17 "Player/BIS_fnc_log: [postInit] ExileServer_fnc_postInit (0 ms)"
13:45:17 "Player/BIS_fnc_log: [BIS_fnc_preload] ----- Scripts initialized at 684.937 ms -----"
13:45:19 Game started.
13:45:33 Player Boba Fett disconnected.
13:45:33 BattlEye Server: Player #0 Boba Fett disconnected
13:45:33 All users disconnected, waiting for users.

**Comment by Torndeco** [comment]
Extension is fine, the error is bad logic in the SQF code.
You need togo to Exile forums for support etc

**Comment by MattDogIRC** [comment]
thanks i figured it out it was looking for exile database which doesn't exist stupid file don't check a config file to see what it's database is lol
