### ISSUE TITLE
Accidently the Wiki

### ISSUE THREAD

**Issue by alexcroox** [Torndeco/extDB2#97]
So erm, I accidentally edited one of your Wiki pages. I didn't think clicking save on the edit would actually save, I presumed edits wouldn't be so open to abuse (maybe a pull request type system).

https://github.com/Torndeco/extDB2/wiki/Calls:-Protocol-HTTP_RAW

I've tried to revert back to a previous version with little success.

Sorry!

**Comment by Torndeco** [comment]
Its fine.
Anyway that got removed awhile ago from extDB2...
So have just deleted the wiki page
