### ISSUE TITLE
FEATURE REQ: Status request for MISC, STEAM and LOG

### ISSUE THREAD

**Issue by TheTotenkopf** [Torndeco/extDB2#98]
Huhu,

wäre super wenn man nicht nur RCON und den LOCK Status abfragen könnte. Die obengennanten Abfragen wären super.

**Comment by chris579** [comment]
Please write in English (I'm German but Torndeco isn't) 

I don't see why it is needed to check the status of these protocols. For RCON it's just implemented because a valid RCON connection could last a bit of time. All other protocols work instant so you can do this via SQF.

**Comment by TheTotenkopf** [comment]
Well I thought Torndeco is German ... damn

I need this option just for cosmetic reasons.

Like this:

	// START MISC API FOR EXTDB
	if(getNumber(configFile >> "CfgServerSettings" >> "DATABASE" >> "MISC") isEqualTo 1) then {
		MISC_ID = round(random(999999));
		__SCVAR__(MISC_ID);
		uiNamespace setVariable ["MISC_ID",MISC_ID];
		"extDB2" callExtension format["9:ADD_PROTOCOL:MISC:%1",(call MISC_ID)];
		diag_log "EXTDB:: MISC IS ENABLED";
		_serverTime = "extDB2" callExtension format["0:%1:TIME:1",(call MISC_ID)];
		diag_log format ["EXTDB::: GLOBAL TIME (GMT+1): %1",_serverTime];
	};
	// START RCON API FOR EXTDB
	if(getNumber(configFile >> "CfgServerSettings" >> "DATABASE" >> "RCON") isEqualTo 1) then {
		RCON_ID = round(random(999999));
		__SCVAR__(RCON_ID);
		uiNamespace setVariable ["RCON_ID",RCON_ID];
		"extDB2" callExtension "9:START_RCON:RCON";
		"extDB2" callExtension format["9:ADD_PROTOCOL:RCON:%1",(call RCON_ID)];
		_rconStatus = "extDB2" callExtension "9:RCON_STATUS";
		if(_rconStatus isEqualTo "[1]") then { 
			diag_log "EXTDB:: RCON IS ENABLED";
		} else {
			diag_log "EXTDB:: RCON DISABLED";
		};
	};

MISC could probably fail and the log say that MISC is loaded successfull thats "stupid" :1234:

**Comment by chris579** [comment]
If it failed you did something wrong. Return value is "[1,[]]" if init succeed otherwise it's "[0,[]]". You can check it this way. Quite simple.
